<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Descriptive Statistics and T-tests in R | Introduction to R</title>
  <meta name="description" content="This GitBook is for the R Workshops" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Descriptive Statistics and T-tests in R | Introduction to R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This GitBook is for the R Workshops" />
  <meta name="github-repo" content="ryandonovan93/rintro" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Descriptive Statistics and T-tests in R | Introduction to R" />
  
  <meta name="twitter:description" content="This GitBook is for the R Workshops" />
  

<meta name="author" content="Ryan Donovan" />


<meta name="date" content="2024-10-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-vis.html"/>
<link rel="next" href="appendix---understanding-boolean-operators-in-the-context-of-filter.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to R (University of Galway)</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> <strong>Introduction</strong></a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#who-is-this-resource-for"><i class="fa fa-check"></i><b>1.1</b> Who is this resource for?</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#should-i-learn-r"><i class="fa fa-check"></i><b>1.2</b> Should I learn R?</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#what-will-i-learn-to-do-in-r"><i class="fa fa-check"></i><b>1.3</b> What will I learn to do in R?</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#what-will-i-not-learn-to-do-in-r"><i class="fa fa-check"></i><b>1.4</b> What will I not learn to do in R?</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#where-and-when-will-the-workshops-take-place"><i class="fa fa-check"></i><b>1.5</b> Where and when will the workshops take place?</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#are-there-any-prerequisites-for-taking-this-course"><i class="fa fa-check"></i><b>1.6</b> Are there any prerequisites for taking this course?</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#do-i-need-to-bring-a-laptop-to-the-class"><i class="fa fa-check"></i><b>1.7</b> Do I need to bring a laptop to the class?</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rstudio.html"><a href="rstudio.html"><i class="fa fa-check"></i><b>2</b> <strong>Getting Started with R and RStudio</strong></a>
<ul>
<li class="chapter" data-level="2.1" data-path="rstudio.html"><a href="rstudio.html#what-is-r"><i class="fa fa-check"></i><b>2.1</b> What is R?</a></li>
<li class="chapter" data-level="2.2" data-path="rstudio.html"><a href="rstudio.html#create-a-posit-cloud-account."><i class="fa fa-check"></i><b>2.2</b> Create a Posit Cloud Account.</a></li>
<li class="chapter" data-level="2.3" data-path="rstudio.html"><a href="rstudio.html#downloading-r-on-to-your-computer"><i class="fa fa-check"></i><b>2.3</b> Downloading R on to your Computer</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="rstudio.html"><a href="rstudio.html#downloading-r-on-windows"><i class="fa fa-check"></i><b>2.3.1</b> Downloading R on Windows</a></li>
<li class="chapter" data-level="2.3.2" data-path="rstudio.html"><a href="rstudio.html#downloading-r-on-mac"><i class="fa fa-check"></i><b>2.3.2</b> Downloading R on Mac</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="rstudio.html"><a href="rstudio.html#install-and-open-r-studio"><i class="fa fa-check"></i><b>2.4</b> Install and Open R Studio</a></li>
<li class="chapter" data-level="2.5" data-path="rstudio.html"><a href="rstudio.html#creating-an-r-project"><i class="fa fa-check"></i><b>2.5</b> Creating an R Project</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="rstudio.html"><a href="rstudio.html#navigating-rstudio"><i class="fa fa-check"></i><b>2.5.1</b> Navigating RStudio</a></li>
<li class="chapter" data-level="2.5.2" data-path="rstudio.html"><a href="rstudio.html#checking-our-working-directory"><i class="fa fa-check"></i><b>2.5.2</b> Checking our Working Directory</a></li>
<li class="chapter" data-level="2.5.3" data-path="rstudio.html"><a href="rstudio.html#set_wd"><i class="fa fa-check"></i><b>2.5.3</b> Setting up a new Working Directory</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="rstudio.html"><a href="rstudio.html#writing-our-first-r-code"><i class="fa fa-check"></i><b>2.6</b> Writing our first R Code</a></li>
<li class="chapter" data-level="2.7" data-path="rstudio.html"><a href="rstudio.html#console-vs-source-script"><i class="fa fa-check"></i><b>2.7</b> Console vs Source Script</a></li>
<li class="chapter" data-level="2.8" data-path="rstudio.html"><a href="rstudio.html#firstpieceofcode"><i class="fa fa-check"></i><b>2.8</b> Let’s write some statistical code</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="rstudio.html"><a href="rstudio.html#comments"><i class="fa fa-check"></i><b>2.8.1</b> Comments</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="rstudio.html"><a href="rstudio.html#summary"><i class="fa fa-check"></i><b>2.9</b> Summary</a></li>
<li class="chapter" data-level="2.10" data-path="rstudio.html"><a href="rstudio.html#glossary"><i class="fa fa-check"></i><b>2.10</b> Glossary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="programming1.html"><a href="programming1.html"><i class="fa fa-check"></i><b>3</b> <strong>R Programming (Part I)</strong></a>
<ul>
<li class="chapter" data-level="3.1" data-path="programming1.html"><a href="programming1.html#activity-1-set-up-your-working-directory"><i class="fa fa-check"></i><b>3.1</b> Activity 1: Set up your Working Directory</a></li>
<li class="chapter" data-level="3.2" data-path="programming1.html"><a href="programming1.html#using-the-console"><i class="fa fa-check"></i><b>3.2</b> Using the Console</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="programming1.html"><a href="programming1.html#typing-commands-in-the-console"><i class="fa fa-check"></i><b>3.2.1</b> Typing Commands in the Console</a></li>
<li class="chapter" data-level="3.2.2" data-path="programming1.html"><a href="programming1.html#console-syntax-aka-im-ron-burgundy"><i class="fa fa-check"></i><b>3.2.2</b> Console Syntax (Aka “I’m Ron Burgundy?”)</a></li>
<li class="chapter" data-level="3.2.3" data-path="programming1.html"><a href="programming1.html#exercises"><i class="fa fa-check"></i><b>3.2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="programming1.html"><a href="programming1.html#data-types"><i class="fa fa-check"></i><b>3.3</b> Data Types</a></li>
<li class="chapter" data-level="3.4" data-path="programming1.html"><a href="programming1.html#basic-data-types-in-r"><i class="fa fa-check"></i><b>3.4</b> Basic Data types in R</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="programming1.html"><a href="programming1.html#character"><i class="fa fa-check"></i><b>3.4.1</b> Character</a></li>
<li class="chapter" data-level="3.4.2" data-path="programming1.html"><a href="programming1.html#numeric-or-double"><i class="fa fa-check"></i><b>3.4.2</b> Numeric (or Double)</a></li>
<li class="chapter" data-level="3.4.3" data-path="programming1.html"><a href="programming1.html#integer"><i class="fa fa-check"></i><b>3.4.3</b> Integer</a></li>
<li class="chapter" data-level="3.4.4" data-path="programming1.html"><a href="programming1.html#logical-otherwise-know-as-boolean"><i class="fa fa-check"></i><b>3.4.4</b> Logical (otherwise know as Boolean)</a></li>
<li class="chapter" data-level="3.4.5" data-path="programming1.html"><a href="programming1.html#exercises-1"><i class="fa fa-check"></i><b>3.4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="programming1.html"><a href="programming1.html#variables"><i class="fa fa-check"></i><b>3.5</b> Variables</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="programming1.html"><a href="programming1.html#whats-in-a-name-conventions-for-naming-variables"><i class="fa fa-check"></i><b>3.5.1</b> What’s in a name? (Conventions for Naming Variables)</a></li>
<li class="chapter" data-level="3.5.2" data-path="programming1.html"><a href="programming1.html#exercises-2"><i class="fa fa-check"></i><b>3.5.2</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="programming1.html"><a href="programming1.html#data-structures"><i class="fa fa-check"></i><b>3.6</b> Data Structures</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="programming1.html"><a href="programming1.html#vectors"><i class="fa fa-check"></i><b>3.6.1</b> Vectors</a></li>
<li class="chapter" data-level="3.6.2" data-path="programming1.html"><a href="programming1.html#data-frames"><i class="fa fa-check"></i><b>3.6.2</b> Data frames</a></li>
<li class="chapter" data-level="3.6.3" data-path="programming1.html"><a href="programming1.html#exercises-3"><i class="fa fa-check"></i><b>3.6.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="programming1.html"><a href="programming1.html#summary-1"><i class="fa fa-check"></i><b>3.7</b> Summary</a></li>
<li class="chapter" data-level="3.8" data-path="programming1.html"><a href="programming1.html#glossary-1"><i class="fa fa-check"></i><b>3.8</b> Glossary</a></li>
<li class="chapter" data-level="3.9" data-path="programming1.html"><a href="programming1.html#variable-name-table"><i class="fa fa-check"></i><b>3.9</b> Variable Name Table</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="programming2.html"><a href="programming2.html"><i class="fa fa-check"></i><b>4</b> <strong>R Programming (Part II)</strong></a>
<ul>
<li class="chapter" data-level="4.1" data-path="programming2.html"><a href="programming2.html#functions"><i class="fa fa-check"></i><b>4.1</b> Functions</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="programming2.html"><a href="programming2.html#the-syntax-for-creating-a-function"><i class="fa fa-check"></i><b>4.1.1</b> The Syntax for Creating a Function</a></li>
<li class="chapter" data-level="4.1.2" data-path="programming2.html"><a href="programming2.html#creating-a-simple-function-1-argument"><i class="fa fa-check"></i><b>4.1.2</b> Creating a Simple Function (1-Argument)</a></li>
<li class="chapter" data-level="4.1.3" data-path="programming2.html"><a href="programming2.html#creating-a-multi-argument-function"><i class="fa fa-check"></i><b>4.1.3</b> Creating a Multi-Argument Function</a></li>
<li class="chapter" data-level="4.1.4" data-path="programming2.html"><a href="programming2.html#functions-inside-functions"><i class="fa fa-check"></i><b>4.1.4</b> Functions inside Functions</a></li>
<li class="chapter" data-level="4.1.5" data-path="programming2.html"><a href="programming2.html#returning-multiple-objects-from-a-function"><i class="fa fa-check"></i><b>4.1.5</b> Returning Multiple Objects from a Function</a></li>
<li class="chapter" data-level="4.1.6" data-path="programming2.html"><a href="programming2.html#some-important-features-about-functions"><i class="fa fa-check"></i><b>4.1.6</b> Some Important Features about Functions</a></li>
<li class="chapter" data-level="4.1.7" data-path="programming2.html"><a href="programming2.html#exercises-4"><i class="fa fa-check"></i><b>4.1.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="programming2.html"><a href="programming2.html#the-factor-data-type"><i class="fa fa-check"></i><b>4.2</b> The Factor Data Type</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="programming2.html"><a href="programming2.html#creating-a-factor"><i class="fa fa-check"></i><b>4.2.1</b> Creating a Factor</a></li>
<li class="chapter" data-level="4.2.2" data-path="programming2.html"><a href="programming2.html#using-factors-to-sort-character-data"><i class="fa fa-check"></i><b>4.2.2</b> Using Factors to Sort Character Data</a></li>
<li class="chapter" data-level="4.2.3" data-path="programming2.html"><a href="programming2.html#exercises-5"><i class="fa fa-check"></i><b>4.2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="programming2.html"><a href="programming2.html#the-list-data-structure"><i class="fa fa-check"></i><b>4.3</b> The List Data Structure</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="programming2.html"><a href="programming2.html#understanding-lists"><i class="fa fa-check"></i><b>4.3.1</b> Understanding Lists</a></li>
<li class="chapter" data-level="4.3.2" data-path="programming2.html"><a href="programming2.html#creating-lists"><i class="fa fa-check"></i><b>4.3.2</b> Creating Lists</a></li>
<li class="chapter" data-level="4.3.3" data-path="programming2.html"><a href="programming2.html#lists-within-lists-indexing"><i class="fa fa-check"></i><b>4.3.3</b> Lists within Lists (Indexing)</a></li>
<li class="chapter" data-level="4.3.4" data-path="programming2.html"><a href="programming2.html#summary-2"><i class="fa fa-check"></i><b>4.3.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="programming2.html"><a href="programming2.html#r-packages"><i class="fa fa-check"></i><b>4.4</b> R Packages</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="programming2.html"><a href="programming2.html#understanding-r-packages"><i class="fa fa-check"></i><b>4.4.1</b> Understanding R Packages</a></li>
<li class="chapter" data-level="4.4.2" data-path="programming2.html"><a href="programming2.html#installing-and-loading-r-package"><i class="fa fa-check"></i><b>4.4.2</b> Installing and Loading R Package</a></li>
<li class="chapter" data-level="4.4.3" data-path="programming2.html"><a href="programming2.html#loading-packages"><i class="fa fa-check"></i><b>4.4.3</b> Loading Packages</a></li>
<li class="chapter" data-level="4.4.4" data-path="programming2.html"><a href="programming2.html#testing-our-new-functions"><i class="fa fa-check"></i><b>4.4.4</b> Testing our New Functions</a></li>
<li class="chapter" data-level="4.4.5" data-path="programming2.html"><a href="programming2.html#error-loading-packages"><i class="fa fa-check"></i><b>4.4.5</b> Error Loading Packages</a></li>
<li class="chapter" data-level="4.4.6" data-path="programming2.html"><a href="programming2.html#package-conventions-if-using-code"><i class="fa fa-check"></i><b>4.4.6</b> Package Conventions if Using Code</a></li>
<li class="chapter" data-level="4.4.7" data-path="programming2.html"><a href="programming2.html#summary-3"><i class="fa fa-check"></i><b>4.4.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="programming2.html"><a href="programming2.html#importing"><i class="fa fa-check"></i><b>4.5</b> Importing and Exporting Data</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="programming2.html"><a href="programming2.html#importing-csv-files."><i class="fa fa-check"></i><b>4.5.1</b> Importing CSV files.</a></li>
<li class="chapter" data-level="4.5.2" data-path="programming2.html"><a href="programming2.html#importing-spss-.sav-files."><i class="fa fa-check"></i><b>4.5.2</b> Importing SPSS (.sav files).</a></li>
<li class="chapter" data-level="4.5.3" data-path="programming2.html"><a href="programming2.html#exporting-datasets-in-r"><i class="fa fa-check"></i><b>4.5.3</b> Exporting Datasets in R</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="programming2.html"><a href="programming2.html#summary-4"><i class="fa fa-check"></i><b>4.6</b> Summary</a></li>
<li class="chapter" data-level="4.7" data-path="programming2.html"><a href="programming2.html#glossary-2"><i class="fa fa-check"></i><b>4.7</b> Glossary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="datacleaning1.html"><a href="datacleaning1.html"><i class="fa fa-check"></i><b>5</b> <strong>Data Wrangling and Cleaning (Part I)</strong></a>
<ul>
<li class="chapter" data-level="5.1" data-path="datacleaning1.html"><a href="datacleaning1.html#what-is-data-wrangling-and-cleaning"><i class="fa fa-check"></i><b>5.1</b> <strong>What is Data Wrangling and Cleaning?</strong></a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="datacleaning1.html"><a href="datacleaning1.html#naming-conventions-in-this-book"><i class="fa fa-check"></i><b>5.1.1</b> <strong>Naming Conventions in this Book</strong></a></li>
<li class="chapter" data-level="5.1.2" data-path="datacleaning1.html"><a href="datacleaning1.html#why-is-data-cleaning-important"><i class="fa fa-check"></i><b>5.1.2</b> <strong>Why is Data Cleaning Important?</strong></a></li>
<li class="chapter" data-level="5.1.3" data-path="datacleaning1.html"><a href="datacleaning1.html#how-can-r-help-you-with-data-cleaning"><i class="fa fa-check"></i><b>5.1.3</b> <strong>How can R help you with Data Cleaning?</strong></a></li>
<li class="chapter" data-level="5.1.4" data-path="datacleaning1.html"><a href="datacleaning1.html#tidyverse-and-base-r"><i class="fa fa-check"></i><b>5.1.4</b> Tidyverse (and Base R)</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="datacleaning1.html"><a href="datacleaning1.html#lets-get-set-up"><i class="fa fa-check"></i><b>5.2</b> Let’s Get Set Up</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="datacleaning1.html"><a href="datacleaning1.html#activity-1.1-set-up-your-wd"><i class="fa fa-check"></i><b>5.2.1</b> Activity 1.1: Set up your WD</a></li>
<li class="chapter" data-level="5.2.2" data-path="datacleaning1.html"><a href="datacleaning1.html#activity-1.2-import-your-csv-files-and-r-script"><i class="fa fa-check"></i><b>5.2.2</b> Activity 1.2: Import your CSV files and R script</a></li>
<li class="chapter" data-level="5.2.3" data-path="datacleaning1.html"><a href="datacleaning1.html#activity-1.3-install-and-load-the-tidyverse-package"><i class="fa fa-check"></i><b>5.2.3</b> Activity 1.3: Install and load the tidyverse package</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="datacleaning1.html"><a href="datacleaning1.html#cleaning-the-remote-associates-data-set."><i class="fa fa-check"></i><b>5.3</b> Cleaning the Remote Associates Data set.</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="datacleaning1.html"><a href="datacleaning1.html#context-and-viewing-it-in-rstudio"><i class="fa fa-check"></i><b>5.3.1</b> Context and Viewing it in RStudio</a></li>
<li class="chapter" data-level="5.3.2" data-path="datacleaning1.html"><a href="datacleaning1.html#key-functions-that-will-help-you-clean-most-datasets"><i class="fa fa-check"></i><b>5.3.2</b> Key Functions That Will Help You Clean Most Datasets</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="datacleaning1.html"><a href="datacleaning1.html#choosing-our-columns-of-interest-with-select"><i class="fa fa-check"></i><b>5.4</b> Choosing our Columns of Interest with <code>Select()</code></a></li>
<li class="chapter" data-level="5.5" data-path="datacleaning1.html"><a href="datacleaning1.html#renaming-our-columns-of-interest-with-rename"><i class="fa fa-check"></i><b>5.5</b> Renaming our Columns of Interest with <code>rename()</code></a></li>
<li class="chapter" data-level="5.6" data-path="datacleaning1.html"><a href="datacleaning1.html#creating-new-columns-using-the-mutate-function"><i class="fa fa-check"></i><b>5.6</b> Creating new Columns using the <code>mutate()</code> function</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="datacleaning1.html"><a href="datacleaning1.html#rewriting-existing-columns-using-mutate"><i class="fa fa-check"></i><b>5.6.1</b> Rewriting existing columns using <code>mutate()</code></a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="datacleaning1.html"><a href="datacleaning1.html#checking-in-on-our-data-set"><i class="fa fa-check"></i><b>5.7</b> Checking in on our data set</a></li>
<li class="chapter" data-level="5.8" data-path="datacleaning1.html"><a href="datacleaning1.html#removing-duplicates-using-distinct"><i class="fa fa-check"></i><b>5.8</b> Removing Duplicates using <code>distinct()</code></a></li>
<li class="chapter" data-level="5.9" data-path="datacleaning1.html"><a href="datacleaning1.html#removing-rows-using-the-filter-function"><i class="fa fa-check"></i><b>5.9</b> Removing Rows using the <code>filter()</code> Function</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="datacleaning1.html"><a href="datacleaning1.html#removing-rows-using-multiple-conditions-with-filter"><i class="fa fa-check"></i><b>5.9.1</b> Removing Rows Using Multiple Conditions with <code>filter()</code></a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="datacleaning1.html"><a href="datacleaning1.html#identifying-the-factors-in-our-data-frame"><i class="fa fa-check"></i><b>5.10</b> Identifying the Factors in our Data Frame</a></li>
<li class="chapter" data-level="5.11" data-path="datacleaning1.html"><a href="datacleaning1.html#summarising-our-data-by-groups-using-group_by-and-summarise"><i class="fa fa-check"></i><b>5.11</b> Summarising our Data by Groups using <code>group_by()</code> and <code>summarise()</code></a></li>
<li class="chapter" data-level="5.12" data-path="datacleaning1.html"><a href="datacleaning1.html#chaining-it-all-together-with-the-pipe-operator"><i class="fa fa-check"></i><b>5.12</b> Chaining it All Together with the Pipe Operator</a>
<ul>
<li class="chapter" data-level="5.12.1" data-path="datacleaning1.html"><a href="datacleaning1.html#using-a-pipe-operator-on-the-remote-associations-data-frame"><i class="fa fa-check"></i><b>5.12.1</b> Using a Pipe Operator on the Remote Associations Data Frame</a></li>
</ul></li>
<li class="chapter" data-level="5.13" data-path="datacleaning1.html"><a href="datacleaning1.html#clean-activity"><i class="fa fa-check"></i><b>5.13</b> Activity: Clean the Flanker Dataset</a>
<ul>
<li class="chapter" data-level="5.13.1" data-path="datacleaning1.html"><a href="datacleaning1.html#cleaning-flanker-test-dataset"><i class="fa fa-check"></i><b>5.13.1</b> <strong>Cleaning Flanker Test Dataset</strong></a></li>
<li class="chapter" data-level="5.13.2" data-path="datacleaning1.html"><a href="datacleaning1.html#load-the-tidyverse-package"><i class="fa fa-check"></i><b>5.13.2</b> <strong>Load the “Tidyverse” Package</strong></a></li>
<li class="chapter" data-level="5.13.3" data-path="datacleaning1.html"><a href="datacleaning1.html#reset-your-environment"><i class="fa fa-check"></i><b>5.13.3</b> <strong>Reset Your Environment</strong></a></li>
<li class="chapter" data-level="5.13.4" data-path="datacleaning1.html"><a href="datacleaning1.html#import-the-data"><i class="fa fa-check"></i><b>5.13.4</b> <strong>Import the Data</strong></a></li>
<li class="chapter" data-level="5.13.5" data-path="datacleaning1.html"><a href="datacleaning1.html#cleaning-instructions"><i class="fa fa-check"></i><b>5.13.5</b> Cleaning Instructions</a></li>
</ul></li>
<li class="chapter" data-level="5.14" data-path="datacleaning1.html"><a href="datacleaning1.html#summary-5"><i class="fa fa-check"></i><b>5.14</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datacleaning2.html"><a href="datacleaning2.html"><i class="fa fa-check"></i><b>6</b> Data Wrangling and Cleaning (Part II)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="datacleaning2.html"><a href="datacleaning2.html#lets-get-set-up-1"><i class="fa fa-check"></i><b>6.1</b> Let’s Get Set Up</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="datacleaning2.html"><a href="datacleaning2.html#activity-1.1-set-up-your-wd-1"><i class="fa fa-check"></i><b>6.1.1</b> Activity 1.1: Set up your WD</a></li>
<li class="chapter" data-level="6.1.2" data-path="datacleaning2.html"><a href="datacleaning2.html#activity-1.2-import-your-csv-files-and-r-script-1"><i class="fa fa-check"></i><b>6.1.2</b> Activity 1.2: Import your CSV files and R script</a></li>
<li class="chapter" data-level="6.1.3" data-path="datacleaning2.html"><a href="datacleaning2.html#activity-1.3-load-the-tidyverse-package"><i class="fa fa-check"></i><b>6.1.3</b> Activity 1.3: Load the tidyverse package</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="datacleaning2.html"><a href="datacleaning2.html#dataformats"><i class="fa fa-check"></i><b>6.2</b> Data Formats (Long and Wide Data)</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="datacleaning2.html"><a href="datacleaning2.html#defining-long-and-wide-data"><i class="fa fa-check"></i><b>6.2.1</b> Defining Long and Wide Data</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="datacleaning2.html"><a href="datacleaning2.html#converting-the-format-of-our-data"><i class="fa fa-check"></i><b>6.3</b> Converting the Format of Our Data</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="datacleaning2.html"><a href="datacleaning2.html#pivoting-from-wide-to-long"><i class="fa fa-check"></i><b>6.3.1</b> Pivoting from Wide to Long</a></li>
<li class="chapter" data-level="6.3.2" data-path="datacleaning2.html"><a href="datacleaning2.html#pivoting-our-remote-associations-data-frame"><i class="fa fa-check"></i><b>6.3.2</b> Pivoting our Remote Associations Data Frame</a></li>
<li class="chapter" data-level="6.3.3" data-path="datacleaning2.html"><a href="datacleaning2.html#pivoting-from-long-to-wide"><i class="fa fa-check"></i><b>6.3.3</b> Pivoting from Long to Wide</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="datacleaning2.html"><a href="datacleaning2.html#handling-missing-values"><i class="fa fa-check"></i><b>6.4</b> Handling Missing Values</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="datacleaning2.html"><a href="datacleaning2.html#introduction-to-missing-values"><i class="fa fa-check"></i><b>6.4.1</b> <strong>Introduction to Missing Values</strong></a></li>
<li class="chapter" data-level="6.4.2" data-path="datacleaning2.html"><a href="datacleaning2.html#identifying-missing-values"><i class="fa fa-check"></i><b>6.4.2</b> <strong>Identifying Missing Values</strong></a></li>
<li class="chapter" data-level="6.4.3" data-path="datacleaning2.html"><a href="datacleaning2.html#removing-missing-values"><i class="fa fa-check"></i><b>6.4.3</b> Removing Missing Values</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="datacleaning2.html"><a href="datacleaning2.html#merging-data-i.e.-joining-different-datasets-together"><i class="fa fa-check"></i><b>6.5</b> Merging Data (i.e., Joining Different Datasets Together)</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="datacleaning2.html"><a href="datacleaning2.html#introduction-to-merging-data"><i class="fa fa-check"></i><b>6.5.1</b> Introduction to Merging Data</a></li>
<li class="chapter" data-level="6.5.2" data-path="datacleaning2.html"><a href="datacleaning2.html#inner_join"><i class="fa fa-check"></i><b>6.5.2</b> Inner_Join</a></li>
<li class="chapter" data-level="6.5.3" data-path="datacleaning2.html"><a href="datacleaning2.html#left_join"><i class="fa fa-check"></i><b>6.5.3</b> Left_join</a></li>
<li class="chapter" data-level="6.5.4" data-path="datacleaning2.html"><a href="datacleaning2.html#right_join"><i class="fa fa-check"></i><b>6.5.4</b> Right_Join</a></li>
<li class="chapter" data-level="6.5.5" data-path="datacleaning2.html"><a href="datacleaning2.html#outer-join"><i class="fa fa-check"></i><b>6.5.5</b> Outer Join</a></li>
<li class="chapter" data-level="6.5.6" data-path="datacleaning2.html"><a href="datacleaning2.html#summary-7"><i class="fa fa-check"></i><b>6.5.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="datacleaning2.html"><a href="datacleaning2.html#data-wrangling-example-demographic-and-flanker-task"><i class="fa fa-check"></i><b>6.6</b> Data Wrangling Example (Demographic and Flanker Task)</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="datacleaning2.html"><a href="datacleaning2.html#part-i-cleaning-the-df_background-file"><i class="fa fa-check"></i><b>6.6.1</b> Part I: Cleaning the <code>df_background</code> file</a></li>
<li class="chapter" data-level="6.6.2" data-path="datacleaning2.html"><a href="datacleaning2.html#cleaning-our-flanker-tasks"><i class="fa fa-check"></i><b>6.6.2</b> Cleaning our Flanker Tasks</a></li>
<li class="chapter" data-level="6.6.3" data-path="datacleaning2.html"><a href="datacleaning2.html#merging-the-data-frames"><i class="fa fa-check"></i><b>6.6.3</b> Merging the Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="datacleaning2.html"><a href="datacleaning2.html#summary-8"><i class="fa fa-check"></i><b>6.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-vis.html"><a href="data-vis.html"><i class="fa fa-check"></i><b>7</b> Data Visualisation in R</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-vis.html"><a href="data-vis.html#lets-get-set-up-2"><i class="fa fa-check"></i><b>7.1</b> Let’s Get Set Up</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="data-vis.html"><a href="data-vis.html#activity-set-up-your-working-directory"><i class="fa fa-check"></i><b>7.1.1</b> Activity: Set Up Your Working Directory</a></li>
<li class="chapter" data-level="7.1.2" data-path="data-vis.html"><a href="data-vis.html#activity-download-and-import-your-files"><i class="fa fa-check"></i><b>7.1.2</b> Activity: Download and Import Your Files</a></li>
<li class="chapter" data-level="7.1.3" data-path="data-vis.html"><a href="data-vis.html#activity-open-your-r-script"><i class="fa fa-check"></i><b>7.1.3</b> Activity: Open your R Script</a></li>
<li class="chapter" data-level="7.1.4" data-path="data-vis.html"><a href="data-vis.html#activity-install-and-load-your-packages"><i class="fa fa-check"></i><b>7.1.4</b> Activity: Install and Load Your Packages</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="data-vis.html"><a href="data-vis.html#introduction-to-ggplot2"><i class="fa fa-check"></i><b>7.2</b> Introduction to <code>ggplot2</code></a></li>
<li class="chapter" data-level="7.3" data-path="data-vis.html"><a href="data-vis.html#how-to-draw-a-plot-box-plot"><i class="fa fa-check"></i><b>7.3</b> How to Draw a Plot (Box Plot)</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="data-vis.html"><a href="data-vis.html#first-we-set-up-the-canvas"><i class="fa fa-check"></i><b>7.3.1</b> First we set up the Canvas</a></li>
<li class="chapter" data-level="7.3.2" data-path="data-vis.html"><a href="data-vis.html#creating-our-box-plot"><i class="fa fa-check"></i><b>7.3.2</b> Creating our Box Plot</a></li>
<li class="chapter" data-level="7.3.3" data-path="data-vis.html"><a href="data-vis.html#changing-the-name-of-our-x-axis-and-y-axis"><i class="fa fa-check"></i><b>7.3.3</b> Changing the Name of Our X-Axis and Y-Axis</a></li>
<li class="chapter" data-level="7.3.4" data-path="data-vis.html"><a href="data-vis.html#changing-the-look-theme-of-our-canvas"><i class="fa fa-check"></i><b>7.3.4</b> Changing the Look (Theme) of Our Canvas</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="data-vis.html"><a href="data-vis.html#the-real-power-of-the-ggplot-package---customisation"><i class="fa fa-check"></i><b>7.4</b> The Real Power of the ggplot package - Customisation</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="data-vis.html"><a href="data-vis.html#mapping-aesthetic-properties-like-colour-and-fill-to-our-variables"><i class="fa fa-check"></i><b>7.4.1</b> Mapping Aesthetic Properties (like Colour and Fill) to Our Variables</a></li>
<li class="chapter" data-level="7.4.2" data-path="data-vis.html"><a href="data-vis.html#changing-the-value-of-our-y-axis"><i class="fa fa-check"></i><b>7.4.2</b> Changing the Value of Our Y-Axis</a></li>
<li class="chapter" data-level="7.4.3" data-path="data-vis.html"><a href="data-vis.html#changing-the-orientation"><i class="fa fa-check"></i><b>7.4.3</b> Changing the Orientation</a></li>
<li class="chapter" data-level="7.4.4" data-path="data-vis.html"><a href="data-vis.html#plotting-our-data-points-in-the-graph"><i class="fa fa-check"></i><b>7.4.4</b> Plotting our Data Points in the Graph</a></li>
<li class="chapter" data-level="7.4.5" data-path="data-vis.html"><a href="data-vis.html#adding-statistical-information-to-our-plot"><i class="fa fa-check"></i><b>7.4.5</b> Adding Statistical Information to Our Plot</a></li>
<li class="chapter" data-level="7.4.6" data-path="data-vis.html"><a href="data-vis.html#adding-text-to-our-plot"><i class="fa fa-check"></i><b>7.4.6</b> Adding Text to Our Plot</a></li>
<li class="chapter" data-level="7.4.7" data-path="data-vis.html"><a href="data-vis.html#exporting-our-plot"><i class="fa fa-check"></i><b>7.4.7</b> Exporting our Plot</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="data-vis.html"><a href="data-vis.html#drawing-a-scatter-plot"><i class="fa fa-check"></i><b>7.5</b> Drawing a Scatter Plot</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="data-vis.html"><a href="data-vis.html#context"><i class="fa fa-check"></i><b>7.5.1</b> Context</a></li>
<li class="chapter" data-level="7.5.2" data-path="data-vis.html"><a href="data-vis.html#drawing-our-plot"><i class="fa fa-check"></i><b>7.5.2</b> Drawing our Plot</a></li>
<li class="chapter" data-level="7.5.3" data-path="data-vis.html"><a href="data-vis.html#customising-our-scatterplot-based-on-gender"><i class="fa fa-check"></i><b>7.5.3</b> Customising our Scatterplot based on Gender</a></li>
<li class="chapter" data-level="7.5.4" data-path="data-vis.html"><a href="data-vis.html#faceting"><i class="fa fa-check"></i><b>7.5.4</b> Faceting</a></li>
<li class="chapter" data-level="7.5.5" data-path="data-vis.html"><a href="data-vis.html#combining-charts"><i class="fa fa-check"></i><b>7.5.5</b> Combining Charts</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="data-vis.html"><a href="data-vis.html#violin-charts"><i class="fa fa-check"></i><b>7.6</b> Violin Charts</a></li>
<li class="chapter" data-level="7.7" data-path="data-vis.html"><a href="data-vis.html#bar-chart"><i class="fa fa-check"></i><b>7.7</b> Bar Chart</a></li>
<li class="chapter" data-level="7.8" data-path="data-vis.html"><a href="data-vis.html#histograms"><i class="fa fa-check"></i><b>7.8</b> Histograms</a></li>
<li class="chapter" data-level="7.9" data-path="data-vis.html"><a href="data-vis.html#line-chart"><i class="fa fa-check"></i><b>7.9</b> Line Chart</a></li>
<li class="chapter" data-level="7.10" data-path="data-vis.html"><a href="data-vis.html#making-our-plots-more-inclusive"><i class="fa fa-check"></i><b>7.10</b> Making our Plots more Inclusive</a></li>
<li class="chapter" data-level="7.11" data-path="data-vis.html"><a href="data-vis.html#summary-9"><i class="fa fa-check"></i><b>7.11</b> Summary</a></li>
<li class="chapter" data-level="7.12" data-path="data-vis.html"><a href="data-vis.html#geoms"><i class="fa fa-check"></i><b>7.12</b> Geoms</a></li>
<li class="chapter" data-level="7.13" data-path="data-vis.html"><a href="data-vis.html#themes"><i class="fa fa-check"></i><b>7.13</b> Themes</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="data-vis.html"><a href="data-vis.html#data-vis"><i class="fa fa-check"></i><b>8</b> Descriptive Statistics and T-tests in R</a>
<ul>
<li class="chapter" data-level="8.1" data-path="data-vis.html"><a href="data-vis.html#lets-get-set-up-3"><i class="fa fa-check"></i><b>8.1</b> Let’s Get Set Up</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="data-vis.html"><a href="data-vis.html#set-up-your-working-directory"><i class="fa fa-check"></i><b>8.1.1</b> Set Up Your Working Directory</a></li>
<li class="chapter" data-level="8.1.2" data-path="data-vis.html"><a href="data-vis.html#download-and-import-your-files"><i class="fa fa-check"></i><b>8.1.2</b> Download and Import Your Files</a></li>
<li class="chapter" data-level="8.1.3" data-path="data-vis.html"><a href="data-vis.html#open-the-set-up-r-script"><i class="fa fa-check"></i><b>8.1.3</b> Open the Set-Up R Script</a></li>
<li class="chapter" data-level="8.1.4" data-path="data-vis.html"><a href="data-vis.html#install-and-load-your-packages"><i class="fa fa-check"></i><b>8.1.4</b> Install and Load Your Packages</a></li>
<li class="chapter" data-level="8.1.5" data-path="data-vis.html"><a href="data-vis.html#load-in-the-wellbeing-dataset"><i class="fa fa-check"></i><b>8.1.5</b> Load in the Wellbeing Dataset</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="data-vis.html"><a href="data-vis.html#descriptive-statistics"><i class="fa fa-check"></i><b>8.2</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="8.3" data-path="data-vis.html"><a href="data-vis.html#introducing-the-jmv-package"><i class="fa fa-check"></i><b>8.3</b> Introducing the <code>jmv</code> package</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="data-vis.html"><a href="data-vis.html#using-the-jmv-function-to-generate-descriptive-statistics"><i class="fa fa-check"></i><b>8.3.1</b> Using the <code>jmv</code> function to generate descriptive statistics</a></li>
<li class="chapter" data-level="8.3.2" data-path="data-vis.html"><a href="data-vis.html#using-the-jmv-function-to-generate-graphs"><i class="fa fa-check"></i><b>8.3.2</b> Using the <code>jmv</code> function to generate graphs</a></li>
<li class="chapter" data-level="8.3.3" data-path="data-vis.html"><a href="data-vis.html#exercises-6"><i class="fa fa-check"></i><b>8.3.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="data-vis.html"><a href="data-vis.html#independent-samples-t-test"><i class="fa fa-check"></i><b>8.4</b> Independent Samples T-Test</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="data-vis.html"><a href="data-vis.html#cleaning-our-data-set"><i class="fa fa-check"></i><b>8.4.1</b> Cleaning our Data Set</a></li>
<li class="chapter" data-level="8.4.2" data-path="data-vis.html"><a href="data-vis.html#checking-our-parametric-assumptions"><i class="fa fa-check"></i><b>8.4.2</b> Checking our Parametric Assumptions</a></li>
<li class="chapter" data-level="8.4.3" data-path="data-vis.html"><a href="data-vis.html#checking-for-homogeneity-of-variance"><i class="fa fa-check"></i><b>8.4.3</b> Checking for Homogeneity of Variance</a></li>
<li class="chapter" data-level="8.4.4" data-path="data-vis.html"><a href="data-vis.html#running-an-independent-sample-t-test"><i class="fa fa-check"></i><b>8.4.4</b> Running an Independent Sample T-Test</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="data-vis.html"><a href="data-vis.html#paired-samples-t-test"><i class="fa fa-check"></i><b>8.5</b> Paired-Samples T-Test</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="data-vis.html"><a href="data-vis.html#cleaning-our-data-set-1"><i class="fa fa-check"></i><b>8.5.1</b> Cleaning our Data Set</a></li>
<li class="chapter" data-level="8.5.2" data-path="data-vis.html"><a href="data-vis.html#checking-our-parametric-assumptions-1"><i class="fa fa-check"></i><b>8.5.2</b> Checking our Parametric Assumptions</a></li>
<li class="chapter" data-level="8.5.3" data-path="data-vis.html"><a href="data-vis.html#running-the-test"><i class="fa fa-check"></i><b>8.5.3</b> Running the Test</a></li>
<li class="chapter" data-level="8.5.4" data-path="data-vis.html"><a href="data-vis.html#exercises-7"><i class="fa fa-check"></i><b>8.5.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="data-vis.html"><a href="data-vis.html#power-analysis"><i class="fa fa-check"></i><b>8.6</b> Power Analysis</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="data-vis.html"><a href="data-vis.html#independent-samples-apriori"><i class="fa fa-check"></i><b>8.6.1</b> Independent Samples (Apriori)</a></li>
<li class="chapter" data-level="8.6.2" data-path="data-vis.html"><a href="data-vis.html#paired-samples-apriorio"><i class="fa fa-check"></i><b>8.6.2</b> Paired Samples (Apriorio)</a></li>
<li class="chapter" data-level="8.6.3" data-path="data-vis.html"><a href="data-vis.html#post-hoc-tests"><i class="fa fa-check"></i><b>8.6.3</b> Post-Hoc Tests</a></li>
<li class="chapter" data-level="8.6.4" data-path="data-vis.html"><a href="data-vis.html#exercises-8"><i class="fa fa-check"></i><b>8.6.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="data-vis.html"><a href="data-vis.html#summary-10"><i class="fa fa-check"></i><b>8.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="appendix---understanding-boolean-operators-in-the-context-of-filter.html"><a href="appendix---understanding-boolean-operators-in-the-context-of-filter.html"><i class="fa fa-check"></i><b>9</b> Appendix - Understanding Boolean Operators in the Context of <code>filter()</code></a>
<ul>
<li class="chapter" data-level="9.1" data-path="appendix---understanding-boolean-operators-in-the-context-of-filter.html"><a href="appendix---understanding-boolean-operators-in-the-context-of-filter.html#how-boolean-operators-work"><i class="fa fa-check"></i><b>9.1</b> How Boolean Operators Work:</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="appendix---understanding-boolean-operators-in-the-context-of-filter.html"><a href="appendix---understanding-boolean-operators-in-the-context-of-filter.html#understanding-rs-evaluation-process"><i class="fa fa-check"></i><b>9.1.1</b> Understanding R’s Evaluation Process:</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-vis" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Descriptive Statistics and T-tests in R<a href="data-vis.html#data-vis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this session, we are going to explore how to perform descriptive statistics and conduct both independent and paired-samples t-tests. Earlier in the course, we looked at using base-R for these tasks, but now we will introduce more intuitive and powerful functions that make these processes easier. Additionally, we will learn how to check parametric assumptions in R. By the end of this session, you will be able to:</p>
<ul>
<li>Use the jmv package to run descriptive statistics and check parametric assumptions.</li>
<li>Conduct an independent samples t-test in R.</li>
<li>Conduct a paired-samples t-test in R.</li>
<li>Conduct apriori and post-hoc power analysis in R for t-tests.</li>
</ul>
<p>We’ll also cover correlations and ANOVAs this week, but to keep things organized, we’ll address those in separate chapters.</p>
<div id="lets-get-set-up-3" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Let’s Get Set Up<a href="data-vis.html#lets-get-set-up-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s begin by ensuring your working environment is ready for today’s session. Open RStudio or Posit Cloud and complete the following tasks to set everything up.</p>
<div id="set-up-your-working-directory" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Set Up Your Working Directory<a href="data-vis.html#set-up-your-working-directory" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Create a folder called week7 in your class folder. This will be your working directory for today’s session. To set this folder as your working directory, click Session -&gt; Set Working Directory -&gt; Choose Directory, and select the newly created week7 folder. Click Open to set it as your working directory.</p>
<p>The path to your directory will be printed in the console, and it should look something like this:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="data-vis.html#cb1-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/0131045s/Desktop/Programming/R/Workshops/rintro/week7&quot;</span>) <span class="co">#this specific path will differ based on your folder configuration, but make sure the end part is in `week7`</span></span></code></pre></div>
<p>Make sure the path ends with week7, although your exact path might differ depending on your folder structure.</p>
</div>
<div id="download-and-import-your-files" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Download and Import Your Files<a href="data-vis.html#download-and-import-your-files" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We are going to need the following files for today’s session. You will find them in the Microsoft Teams channel under the heading <code>Week 7 and 8 - Descriptive and Inferential Statistics</code></p>
<ul>
<li><code>01-set-up.R</code></li>
<li><code>02-descriptives.R</code></li>
<li><code>03-t-tests.R</code></li>
<li><code>wellbeing.csv</code></li>
<li><code>psycho.csv</code></li>
</ul>
<p>Download these files onto your computer and move each file to your <code>week7</code> folder.</p>
</div>
<div id="open-the-set-up-r-script" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Open the Set-Up R Script<a href="data-vis.html#open-the-set-up-r-script" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now in RStudio (or posit cloud), open the R script called <code>01-set-up.R</code>. This script will guide you through installing and loading the necessary packages and datasets for today’s exercises.</p>
</div>
<div id="install-and-load-your-packages" class="section level3 hasAnchor" number="8.1.4">
<h3><span class="header-section-number">8.1.4</span> Install and Load Your Packages<a href="data-vis.html#install-and-load-your-packages" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ll be using several R packages to make our analysis easier. The <code>jmv</code> package is particularly helpful for running descriptive statistics and t-tests, while <code>pwr</code> helps us calculate power for our tests. The <code>tidyverse</code> will assist with data cleaning, and <code>car</code> will allow us to check assumptions like homogeneity of variance.</p>
<p>In the <code>01-set-up.R</code> script, type and run the following code under the section labeled <code>#Load in Our Packages</code>:</p>
<p><strong>REMEMBER</strong>: If you encounter an error message like <code>Error in library(package name): there is no packaged called</code>package name``, you’ll need to install the package first by typing the following into your console:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="data-vis.html#cb2-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;package name&quot;</span>) <span class="co">#replace &quot;package name with the actual package!&quot;</span></span></code></pre></div>
<p>For example, if you need to install the <code>jmv</code> package, you would type <code>install.packages("jmv")</code> into the console.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="data-vis.html#cb3-1" tabindex="-1"></a><span class="fu">library</span>(jmv) <span class="co">#this will help us run descriptive statistics</span></span>
<span id="cb3-2"><a href="data-vis.html#cb3-2" tabindex="-1"></a><span class="fu">library</span>(pwr) <span class="co">#this will enable us to conduct power analysis </span></span>
<span id="cb3-3"><a href="data-vis.html#cb3-3" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#this will help us clean data sets </span></span>
<span id="cb3-4"><a href="data-vis.html#cb3-4" tabindex="-1"></a><span class="fu">library</span>(car) <span class="co">#that runs the levenes test</span></span>
<span id="cb3-5"><a href="data-vis.html#cb3-5" tabindex="-1"></a><span class="fu">library</span>(haven) <span class="co">#imports SPSS data</span></span></code></pre></div>
</div>
<div id="load-in-the-wellbeing-dataset" class="section level3 hasAnchor" number="8.1.5">
<h3><span class="header-section-number">8.1.5</span> Load in the Wellbeing Dataset<a href="data-vis.html#load-in-the-wellbeing-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ll be working with a datasets called <code>wellbeing.csv</code> and <code>psycho.csv</code>. In the <code>01-set-up.R</code> script, type the following code under the section labeled <code>#Load in Our Dataset</code> to load the datasets into R:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="data-vis.html#cb4-1" tabindex="-1"></a>df_wellbeing <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;wellbeing.csv&quot;</span>)</span>
<span id="cb4-2"><a href="data-vis.html#cb4-2" tabindex="-1"></a></span>
<span id="cb4-3"><a href="data-vis.html#cb4-3" tabindex="-1"></a>df_psycho <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;psycho.sav&quot;</span>)</span></code></pre></div>
<p>After loading the datasets, it’s always good practice to inspect it before doing any analyses. You can use the <code>head()</code> and <code>str()</code> functions to get an overview of the wellbeing dataset:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="data-vis.html#cb5-1" tabindex="-1"></a><span class="fu">head</span>(df_wellbeing)</span></code></pre></div>
<pre><code>##         id gender   Condition age pain fatigue depr wellb
## 1 20220137 Female No Caffeine  44   69      49   61    52
## 2 20220147 Female No Caffeine  36   37      45   63    57
## 3 20220155   Male No Caffeine  43   32      55   79    35
## 4 20220164 Female No Caffeine  26   38      46   54    72
## 5 20220173 Female No Caffeine  34   35      45   76    45
## 6 20220177 Female No Caffeine  41   48      44   59    69</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="data-vis.html#cb7-1" tabindex="-1"></a><span class="fu">str</span>(df_wellbeing)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    420 obs. of  8 variables:
##  $ id       : int  20220137 20220147 20220155 20220164 20220173 20220177 20220184 20220191 20220199 20220203 ...
##  $ gender   : chr  &quot;Female&quot; &quot;Female&quot; &quot;Male&quot; &quot;Female&quot; ...
##  $ Condition: chr  &quot;No Caffeine&quot; &quot;No Caffeine&quot; &quot;No Caffeine&quot; &quot;No Caffeine&quot; ...
##  $ age      : int  44 36 43 26 34 41 46 45 34 19 ...
##  $ pain     : int  69 37 32 38 35 48 53 42 42 59 ...
##  $ fatigue  : int  49 45 55 46 45 44 51 49 44 48 ...
##  $ depr     : int  61 63 79 54 76 59 77 67 61 62 ...
##  $ wellb    : int  52 57 35 72 45 69 61 59 60 46 ...</code></pre>
<p>From this, you’ll see that our dataset contains 8 columns. We have two character columns (<code>gender</code> and <code>Condition</code>) and five integer columns (<code>id</code>, <code>age</code>, <code>pain</code>, <code>fatigue</code>, <code>depr</code>, and <code>wellb</code>). This data was collected from an experimental study investigating the effects of Caffeine (<code>No Caffeine</code>, <code>Low Caffeine</code>, and <code>High Caffeine</code>) on various outcome variables, including experiences of pain, fatigue, depression, and overall wellbeing. Additionally, participants’ <code>age</code> and <code>Gender</code> were recorded recorded.</p>
<p>As an exercise, try running the <code>head()</code> and <code>str()</code> functions on the <code>df_psycho</code> data set.</p>
<p>Now that our environment is set up and our dataset is loaded, we are ready to dive into descriptive statistics.</p>
</div>
</div>
<div id="descriptive-statistics" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Descriptive Statistics<a href="data-vis.html#descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If you remember back to our first session <a href="rstudio.html#firstpieceofcode">to our first session</a> we used the <code>summary</code> and <code>aggregate</code> functions to compute descriptive statistics. The <code>summary</code> function is useful for quick glance at your variables.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="data-vis.html#cb9-1" tabindex="-1"></a><span class="fu">summary</span>(df_wellbeing)</span></code></pre></div>
<pre><code>##        id              gender           Condition              age       
##  Min.   :20220137   Length:420         Length:420         Min.   :18.00  
##  1st Qu.:20220697   Class :character   Class :character   1st Qu.:25.00  
##  Median :20221312   Mode  :character   Mode  :character   Median :34.00  
##  Mean   :20221301                                         Mean   :34.79  
##  3rd Qu.:20221903                                         3rd Qu.:43.25  
##  Max.   :20222492                                         Max.   :55.00  
##       pain         fatigue           depr           wellb      
##  Min.   :28.0   Min.   :41.00   Min.   :49.00   Min.   :21.00  
##  1st Qu.:33.0   1st Qu.:45.00   1st Qu.:61.00   1st Qu.:51.00  
##  Median :38.0   Median :47.00   Median :66.00   Median :60.00  
##  Mean   :40.6   Mean   :47.95   Mean   :66.14   Mean   :58.52  
##  3rd Qu.:45.0   3rd Qu.:50.00   3rd Qu.:70.00   3rd Qu.:67.00  
##  Max.   :90.0   Max.   :65.00   Max.   :94.00   Max.   :83.00</code></pre>
<p>However, the information we get from <code>summary</code> is limited. It doesn’t provide important measures like the standard deviation or interquartile range, and it can’t be used to generate descriptive statistics for different groups. For that, we need the <code>aggregate</code> function:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="data-vis.html#cb11-1" tabindex="-1"></a><span class="fu">aggregate</span>(df_wellbeing<span class="sc">$</span>age <span class="sc">~</span> df_wellbeing<span class="sc">$</span>Condition, <span class="at">FUN =</span> mean)</span></code></pre></div>
<pre><code>##   df_wellbeing$Condition df_wellbeing$age
## 1          High Caffeine         34.52857
## 2           Low Caffeine         34.01429
## 3            No Caffeine         35.83571</code></pre>
<p>The downside of <code>aggregate</code> is that it computes only one statistic at a time. If you want to calculate the mean, median, and standard deviation, you have to repeat the code for each:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="data-vis.html#cb13-1" tabindex="-1"></a><span class="fu">aggregate</span>(df_wellbeing<span class="sc">$</span>age <span class="sc">~</span> df_wellbeing<span class="sc">$</span>Condition, <span class="at">FUN =</span> mean)</span></code></pre></div>
<pre><code>##   df_wellbeing$Condition df_wellbeing$age
## 1          High Caffeine         34.52857
## 2           Low Caffeine         34.01429
## 3            No Caffeine         35.83571</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="data-vis.html#cb15-1" tabindex="-1"></a><span class="fu">aggregate</span>(df_wellbeing<span class="sc">$</span>age <span class="sc">~</span> df_wellbeing<span class="sc">$</span>Condition, <span class="at">FUN =</span> median)</span></code></pre></div>
<pre><code>##   df_wellbeing$Condition df_wellbeing$age
## 1          High Caffeine             33.5
## 2           Low Caffeine             33.0
## 3            No Caffeine             36.0</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="data-vis.html#cb17-1" tabindex="-1"></a><span class="fu">aggregate</span>(df_wellbeing<span class="sc">$</span>age <span class="sc">~</span> df_wellbeing<span class="sc">$</span>Condition, <span class="at">FUN =</span> sd)</span></code></pre></div>
<pre><code>##   df_wellbeing$Condition df_wellbeing$age
## 1          High Caffeine        10.961307
## 2           Low Caffeine        10.938669
## 3            No Caffeine         9.894123</code></pre>
<p>This approach is cumbersome, especially with larger data sets that contain many variables. Moreover, <code>aggregate</code> doesn’t handle more complex combinations of groups, such as the average age of males in the high-caffeine condition.</p>
</div>
<div id="introducing-the-jmv-package" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Introducing the <code>jmv</code> package<a href="data-vis.html#introducing-the-jmv-package" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <code>jmv</code> package provides a powerful function, <code>descriptives()</code>, which makes descriptive statistics more flexible and comprehensive. It calculates a wide range of statistics across multiple variables and can easily account for different groups. You can even create quick plots as part of the output.</p>
<p>You can get full details of the function by typing <code>?descriptives</code> in your console after loading the package. While the syntax might look complex, it’s actually quite straightforward when you break it down.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="data-vis.html#cb19-1" tabindex="-1"></a><span class="fu">descriptives</span>(data,                      <span class="co"># The dataset you are using</span></span>
<span id="cb19-2"><a href="data-vis.html#cb19-2" tabindex="-1"></a>             vars,                      <span class="co"># The variables you want to calculate descriptives for</span></span>
<span id="cb19-3"><a href="data-vis.html#cb19-3" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="cn">NULL</span>,            <span class="co"># Optional grouping variable; set to NULL if not grouping data</span></span>
<span id="cb19-4"><a href="data-vis.html#cb19-4" tabindex="-1"></a>             <span class="at">freq =</span> <span class="cn">FALSE</span>,              <span class="co"># Whether to show frequency counts (useful for categorical variables)</span></span>
<span id="cb19-5"><a href="data-vis.html#cb19-5" tabindex="-1"></a>             <span class="at">desc =</span> <span class="st">&quot;columns&quot;</span>,          <span class="co"># Orientation of the output (columns vs rows), defaults to columns</span></span>
<span id="cb19-6"><a href="data-vis.html#cb19-6" tabindex="-1"></a>             <span class="at">hist =</span> <span class="cn">FALSE</span>,              <span class="co"># If TRUE, creates histograms for the variables</span></span>
<span id="cb19-7"><a href="data-vis.html#cb19-7" tabindex="-1"></a>             <span class="at">dens =</span> <span class="cn">FALSE</span>,              <span class="co"># If TRUE, plots density estimates</span></span>
<span id="cb19-8"><a href="data-vis.html#cb19-8" tabindex="-1"></a>             <span class="at">bar =</span> <span class="cn">FALSE</span>,               <span class="co"># If TRUE, generates bar charts for the variables</span></span>
<span id="cb19-9"><a href="data-vis.html#cb19-9" tabindex="-1"></a>             <span class="at">barCounts =</span> <span class="cn">FALSE</span>,         <span class="co"># If TRUE, displays counts on the bar chart (only applicable if `bar` is TRUE)</span></span>
<span id="cb19-10"><a href="data-vis.html#cb19-10" tabindex="-1"></a>             <span class="at">box =</span> <span class="cn">FALSE</span>,               <span class="co"># If TRUE, generates box plots for the variables</span></span>
<span id="cb19-11"><a href="data-vis.html#cb19-11" tabindex="-1"></a>             <span class="at">violin =</span> <span class="cn">FALSE</span>,            <span class="co"># If TRUE, creates violin plots to visualize data distribution</span></span>
<span id="cb19-12"><a href="data-vis.html#cb19-12" tabindex="-1"></a>             <span class="at">dot =</span> <span class="cn">FALSE</span>,               <span class="co"># If TRUE, adds dot plots</span></span>
<span id="cb19-13"><a href="data-vis.html#cb19-13" tabindex="-1"></a>             <span class="at">dotType =</span> <span class="st">&quot;jitter&quot;</span>,        <span class="co"># Determines the type of dot plot (e.g., jitter to spread points out)</span></span>
<span id="cb19-14"><a href="data-vis.html#cb19-14" tabindex="-1"></a>             <span class="at">boxMean =</span> <span class="cn">FALSE</span>,           <span class="co"># If TRUE, shows the mean in the box plot</span></span>
<span id="cb19-15"><a href="data-vis.html#cb19-15" tabindex="-1"></a>             <span class="at">boxLabelOutliers =</span> <span class="cn">TRUE</span>,   <span class="co"># If TRUE, labels outliers in the box plot</span></span>
<span id="cb19-16"><a href="data-vis.html#cb19-16" tabindex="-1"></a>             <span class="at">qq =</span> <span class="cn">FALSE</span>,                <span class="co"># If TRUE, generates Q-Q plots for checking normality</span></span>
<span id="cb19-17"><a href="data-vis.html#cb19-17" tabindex="-1"></a>             <span class="at">n =</span> <span class="cn">TRUE</span>,                  <span class="co"># If TRUE, displays the sample size (n) for each variable</span></span>
<span id="cb19-18"><a href="data-vis.html#cb19-18" tabindex="-1"></a>             <span class="at">missing =</span> <span class="cn">TRUE</span>,            <span class="co"># If TRUE, shows the number of missing values for each variable</span></span>
<span id="cb19-19"><a href="data-vis.html#cb19-19" tabindex="-1"></a>             <span class="at">mean =</span> <span class="cn">TRUE</span>,               <span class="co"># If TRUE, displays the mean for each variable</span></span>
<span id="cb19-20"><a href="data-vis.html#cb19-20" tabindex="-1"></a>             <span class="at">median =</span> <span class="cn">TRUE</span>,             <span class="co"># If TRUE, displays the median for each variable</span></span>
<span id="cb19-21"><a href="data-vis.html#cb19-21" tabindex="-1"></a>             <span class="at">mode =</span> <span class="cn">FALSE</span>,              <span class="co"># If TRUE, displays the mode (most frequent value) for each variable</span></span>
<span id="cb19-22"><a href="data-vis.html#cb19-22" tabindex="-1"></a>             <span class="at">sum =</span> <span class="cn">FALSE</span>,               <span class="co"># If TRUE, displays the sum of all values for each variable</span></span>
<span id="cb19-23"><a href="data-vis.html#cb19-23" tabindex="-1"></a>             <span class="at">sd =</span> <span class="cn">TRUE</span>,                 <span class="co"># If TRUE, displays the standard deviation for each variable</span></span>
<span id="cb19-24"><a href="data-vis.html#cb19-24" tabindex="-1"></a>             <span class="at">variance =</span> <span class="cn">FALSE</span>,          <span class="co"># If TRUE, displays the variance for each variable</span></span>
<span id="cb19-25"><a href="data-vis.html#cb19-25" tabindex="-1"></a>             <span class="at">range =</span> <span class="cn">FALSE</span>,             <span class="co"># If TRUE, displays the range (max - min) for each variable</span></span>
<span id="cb19-26"><a href="data-vis.html#cb19-26" tabindex="-1"></a>             <span class="at">min =</span> <span class="cn">TRUE</span>,                <span class="co"># If TRUE, displays the minimum value for each variable</span></span>
<span id="cb19-27"><a href="data-vis.html#cb19-27" tabindex="-1"></a>             <span class="at">max =</span> <span class="cn">TRUE</span>,                <span class="co"># If TRUE, displays the maximum value for each variable</span></span>
<span id="cb19-28"><a href="data-vis.html#cb19-28" tabindex="-1"></a>             <span class="at">se =</span> <span class="cn">FALSE</span>,                <span class="co"># If TRUE, displays the standard error for each variable</span></span>
<span id="cb19-29"><a href="data-vis.html#cb19-29" tabindex="-1"></a>             <span class="at">ci =</span> <span class="cn">FALSE</span>,                <span class="co"># If TRUE, calculates and displays the confidence interval (CI) for each variable</span></span>
<span id="cb19-30"><a href="data-vis.html#cb19-30" tabindex="-1"></a>             <span class="at">ciWidth =</span> <span class="dv">95</span>,              <span class="co"># The width of the confidence interval, defaults to 95%</span></span>
<span id="cb19-31"><a href="data-vis.html#cb19-31" tabindex="-1"></a>             <span class="at">iqr =</span> <span class="cn">FALSE</span>,               <span class="co"># If TRUE, displays the interquartile range (IQR) for each variable</span></span>
<span id="cb19-32"><a href="data-vis.html#cb19-32" tabindex="-1"></a>             <span class="at">skew =</span> <span class="cn">FALSE</span>,              <span class="co"># If TRUE, displays the skewness of the distribution for each variable</span></span>
<span id="cb19-33"><a href="data-vis.html#cb19-33" tabindex="-1"></a>             <span class="at">kurt =</span> <span class="cn">FALSE</span>,              <span class="co"># If TRUE, displays the kurtosis (tailedness) of the distribution for each variable</span></span>
<span id="cb19-34"><a href="data-vis.html#cb19-34" tabindex="-1"></a>             <span class="at">sw =</span> <span class="cn">FALSE</span>,                <span class="co"># If TRUE, runs the Shapiro-Wilk test for normality on each variable</span></span>
<span id="cb19-35"><a href="data-vis.html#cb19-35" tabindex="-1"></a>             <span class="at">pcEqGr =</span> <span class="cn">FALSE</span>,            <span class="co"># If TRUE, calculates percentiles based on equal groupings</span></span>
<span id="cb19-36"><a href="data-vis.html#cb19-36" tabindex="-1"></a>             <span class="at">pcNEqGr =</span> <span class="dv">4</span>,               <span class="co"># The number of equal groups for percentiles (defaults to quartiles)</span></span>
<span id="cb19-37"><a href="data-vis.html#cb19-37" tabindex="-1"></a>             <span class="at">pc =</span> <span class="cn">FALSE</span>,                <span class="co"># If TRUE, calculates specific percentiles (e.g., 25th, 50th, 75th)</span></span>
<span id="cb19-38"><a href="data-vis.html#cb19-38" tabindex="-1"></a>             <span class="at">pcValues =</span> <span class="st">&quot;25,50,75&quot;</span>,     <span class="co"># Specifies which percentiles to calculate (default: 25th, 50th, 75th percentiles)</span></span>
<span id="cb19-39"><a href="data-vis.html#cb19-39" tabindex="-1"></a>             <span class="at">extreme =</span> <span class="cn">FALSE</span>,           <span class="co"># If TRUE, displays extreme values for each variable</span></span>
<span id="cb19-40"><a href="data-vis.html#cb19-40" tabindex="-1"></a>             <span class="at">extremeN =</span> <span class="dv">5</span>,              <span class="co"># The number of extreme values to display for each variable (defaults to 5)</span></span>
<span id="cb19-41"><a href="data-vis.html#cb19-41" tabindex="-1"></a>             formula)                   <span class="co"># Optional argument to specify a formula if using a model</span></span></code></pre></div>
<p>You don’t need to write out all the arguments every time you use <code>descriptives()</code>. You can just specify the dataset and the variables you want to analyse, and everything else will use default settings. If you want to change those defaults, you can simply add the corresponding argument to your code.</p>
<div id="using-the-jmv-function-to-generate-descriptive-statistics" class="section level3 hasAnchor" number="8.3.1">
<h3><span class="header-section-number">8.3.1</span> Using the <code>jmv</code> function to generate descriptive statistics<a href="data-vis.html#using-the-jmv-function-to-generate-descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Open up script <code>02-descriptives.R</code>. In that script, let’s use the <code>descriptives()</code> function to compute statistics for the <code>wellb</code> and <code>depr</code> variables:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="data-vis.html#cb20-1" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data =</span> df_wellbeing, </span>
<span id="cb20-2"><a href="data-vis.html#cb20-2" tabindex="-1"></a>             <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">&quot;wellb&quot;</span>, <span class="st">&quot;depr&quot;</span>))</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                   
##  ────────────────────────────────────────────── 
##                          wellb       depr       
##  ────────────────────────────────────────────── 
##    N                          420         420   
##    Missing                      0           0   
##    Mean                  58.52381    66.14048   
##    Median                60.00000    66.00000   
##    Standard deviation    11.39555    7.629661   
##    Minimum                     21          49   
##    Maximum                     83          94   
##  ──────────────────────────────────────────────</code></pre>
<p>By default, this function displays the sample size (N), number of missing values, mean, median, standard deviation, minimum, and maximum for each variable. If you want to include additional statistics, like the mode, standard error (<code>se</code>) or confidence intervals (<code>ci</code>), you can set those options to <code>TRUE</code>:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="data-vis.html#cb22-1" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data =</span> df_wellbeing, </span>
<span id="cb22-2"><a href="data-vis.html#cb22-2" tabindex="-1"></a>             <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">&quot;wellb&quot;</span>, <span class="st">&quot;depr&quot;</span>),</span>
<span id="cb22-3"><a href="data-vis.html#cb22-3" tabindex="-1"></a>             <span class="at">mode =</span> <span class="cn">TRUE</span>,</span>
<span id="cb22-4"><a href="data-vis.html#cb22-4" tabindex="-1"></a>             <span class="at">se =</span> <span class="cn">TRUE</span>,</span>
<span id="cb22-5"><a href="data-vis.html#cb22-5" tabindex="-1"></a>             <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                          
##  ───────────────────────────────────────────────────── 
##                               wellb        depr        
##  ───────────────────────────────────────────────────── 
##    N                                420          420   
##    Missing                            0            0   
##    Mean                        58.52381     66.14048   
##    Std. error mean            0.5560460    0.3722893   
##    95% CI mean lower bound     57.43082     65.40869   
##    95% CI mean upper bound     59.61680     66.87226   
##    Median                      60.00000     66.00000   
##    Mode                        61.00000     66.00000   
##    Standard deviation          11.39555     7.629661   
##    Minimum                           21           49   
##    Maximum                           83           94   
##  ───────────────────────────────────────────────────── 
##    Note. The CI of the mean assumes sample means
##    follow a t-distribution with N - 1 degrees of
##    freedom</code></pre>
<p>The <code>descriptives</code> function will by default assume you don’t want to split the variables selected in <code>vars</code> by different groups. But we can easily achieve this by using the <code>splitBy</code> argument. In this example, let’s split our descriptive statistics based on participants identified gender.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="data-vis.html#cb24-1" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data =</span> df_wellbeing, </span>
<span id="cb24-2"><a href="data-vis.html#cb24-2" tabindex="-1"></a>             <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">&quot;wellb&quot;</span>, <span class="st">&quot;depr&quot;</span>),</span>
<span id="cb24-3"><a href="data-vis.html#cb24-3" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="fu">c</span>(<span class="st">&quot;gender&quot;</span>), </span>
<span id="cb24-4"><a href="data-vis.html#cb24-4" tabindex="-1"></a>             <span class="at">mode =</span> <span class="cn">TRUE</span>,</span>
<span id="cb24-5"><a href="data-vis.html#cb24-5" tabindex="-1"></a>             <span class="at">se =</span> <span class="cn">TRUE</span>,</span>
<span id="cb24-6"><a href="data-vis.html#cb24-6" tabindex="-1"></a>             <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                                    
##  ─────────────────────────────────────────────────────────────── 
##                               gender    wellb        depr        
##  ─────────────────────────────────────────────────────────────── 
##    N                          Female          260          260   
##                               Male            160          160   
##    Missing                    Female            0            0   
##                               Male              0            0   
##    Mean                       Female     58.83077     65.81923   
##                               Male       58.02500     66.66250   
##    Std. error mean            Female    0.7261969    0.4775088   
##                               Male      0.8604221    0.5936567   
##    95% CI mean lower bound    Female     57.40077     64.87894   
##                               Male       56.32567     65.49003   
##    95% CI mean upper bound    Female     60.26077     66.75952   
##                               Male       59.72433     67.83497   
##    Median                     Female     60.00000     65.00000   
##                               Male       59.00000     66.00000   
##    Mode                       Female     53.00000     66.00000   
##                               Male       61.00000     69.00000   
##    Standard deviation         Female     11.70957     7.699597   
##                               Male       10.88357     7.509229   
##    Minimum                    Female           21           49   
##                               Male             23           51   
##    Maximum                    Female           83           94   
##                               Male             80           94   
##  ─────────────────────────────────────────────────────────────── 
##    Note. The CI of the mean assumes sample means follow a
##    t-distribution with N - 1 degrees of freedom</code></pre>
<p>You can also split by multiple variables. For example, if you want to examine well-being and depression scores by both gender and caffeine conditions:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="data-vis.html#cb26-1" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data =</span> df_wellbeing, </span>
<span id="cb26-2"><a href="data-vis.html#cb26-2" tabindex="-1"></a>             <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">&quot;wellb&quot;</span>, <span class="st">&quot;depr&quot;</span>),</span>
<span id="cb26-3"><a href="data-vis.html#cb26-3" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="fu">c</span>(<span class="st">&quot;gender&quot;</span>, <span class="st">&quot;Condition&quot;</span>),</span>
<span id="cb26-4"><a href="data-vis.html#cb26-4" tabindex="-1"></a>             <span class="at">mode =</span> <span class="cn">TRUE</span>,</span>
<span id="cb26-5"><a href="data-vis.html#cb26-5" tabindex="-1"></a>             <span class="at">se =</span> <span class="cn">TRUE</span>,</span>
<span id="cb26-6"><a href="data-vis.html#cb26-6" tabindex="-1"></a>             <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                                                    
##  ─────────────────────────────────────────────────────────────────────────────── 
##                               gender    Condition        wellb       depr        
##  ─────────────────────────────────────────────────────────────────────────────── 
##    N                          Female    High Caffeine          85           85   
##                                         Low Caffeine           85           85   
##                                         No Caffeine            90           90   
##                               Male      High Caffeine          55           55   
##                                         Low Caffeine           55           55   
##                                         No Caffeine            50           50   
##    Missing                    Female    High Caffeine           0            0   
##                                         Low Caffeine            0            0   
##                                         No Caffeine             0            0   
##                               Male      High Caffeine           0            0   
##                                         Low Caffeine            0            0   
##                                         No Caffeine             0            0   
##    Mean                       Female    High Caffeine    60.42353     64.90588   
##                                         Low Caffeine     56.82353     66.52941   
##                                         No Caffeine      59.22222     66.01111   
##                               Male      High Caffeine    58.38182     67.21818   
##                                         Low Caffeine     58.23636     65.50909   
##                                         No Caffeine      57.40000     67.32000   
##    Std. error mean            Female    High Caffeine    1.303129    0.8167750   
##                                         Low Caffeine     1.363918    0.7934586   
##                                         No Caffeine      1.090966    0.8639679   
##                               Male      High Caffeine    1.392982    0.9508780   
##                                         Low Caffeine     1.424406    0.9159539   
##                                         No Caffeine      1.692239     1.225058   
##    95% CI mean lower bound    Female    High Caffeine    57.83211     63.28164   
##                                         Low Caffeine     54.11123     64.95153   
##                                         No Caffeine      57.05450     64.29443   
##                               Male      High Caffeine    55.58906     65.31179   
##                                         Low Caffeine     55.38060     63.67271   
##                                         No Caffeine      53.99932     64.85815   
##    95% CI mean upper bound    Female    High Caffeine    63.01494     66.53013   
##                                         Low Caffeine     59.53583     68.10729   
##                                         No Caffeine      61.38995     67.72780   
##                               Male      High Caffeine    61.17458     69.12458   
##                                         Low Caffeine     61.09213     67.34547   
##                                         No Caffeine      60.80068     69.78185   
##    Median                     Female    High Caffeine          61           64   
##                                         Low Caffeine           60           66   
##                                         No Caffeine      60.00000     64.50000   
##                               Male      High Caffeine          59           68   
##                                         Low Caffeine           58           65   
##                                         No Caffeine      59.00000     66.00000   
##    Mode                       Female    High Caffeine    53.00000     60.00000   
##                                         Low Caffeine     65.00000     70.00000   
##                                         No Caffeine      60.00000     63.00000   
##                               Male      High Caffeine    61.00000     69.00000   
##                                         Low Caffeine     65.00000     61.00000   
##                                         No Caffeine      70.00000     58.00000   
##    Standard deviation         Female    High Caffeine    12.01425     7.530294   
##                                         Low Caffeine     12.57471     7.315327   
##                                         No Caffeine      10.34981     8.196319   
##                               Male      High Caffeine    10.33063     7.051900   
##                                         Low Caffeine     10.56368     6.792896   
##                                         No Caffeine      11.96594     8.662469   
##    Minimum                    Female    High Caffeine          21           52   
##                                         Low Caffeine           21           49   
##                                         No Caffeine            35           51   
##                               Male      High Caffeine          25           53   
##                                         Low Caffeine           34           51   
##                                         No Caffeine            23           53   
##    Maximum                    Female    High Caffeine          83           85   
##                                         Low Caffeine           77           84   
##                                         No Caffeine            83           94   
##                               Male      High Caffeine          80           83   
##                                         Low Caffeine           77           80   
##                                         No Caffeine            76           94   
##  ─────────────────────────────────────────────────────────────────────────────── 
##    Note. The CI of the mean assumes sample means follow a t-distribution
##    with N - 1 degrees of freedom</code></pre>
<p>This flexibility makes the <code>descriptives()</code> function much more powerful than base R functions like <code>summary()</code> or <code>aggregate()</code><a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>.</p>
</div>
<div id="using-the-jmv-function-to-generate-graphs" class="section level3 hasAnchor" number="8.3.2">
<h3><span class="header-section-number">8.3.2</span> Using the <code>jmv</code> function to generate graphs<a href="data-vis.html#using-the-jmv-function-to-generate-graphs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Another great feature of the <code>descriptives</code> package is that we can also generate plots like box plots, bar charts, or histograms. Let’s use <code>descriptives</code> to calculate descriptive statistics for the <code>fatigue</code> variable based on <code>gender</code> and also generate each plot.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="data-vis.html#cb28-1" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data =</span> df_wellbeing, </span>
<span id="cb28-2"><a href="data-vis.html#cb28-2" tabindex="-1"></a>             <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">&quot;fatigue&quot;</span>),</span>
<span id="cb28-3"><a href="data-vis.html#cb28-3" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="fu">c</span>(<span class="st">&quot;gender&quot;</span>),</span>
<span id="cb28-4"><a href="data-vis.html#cb28-4" tabindex="-1"></a>             <span class="at">box =</span> <span class="cn">TRUE</span>,</span>
<span id="cb28-5"><a href="data-vis.html#cb28-5" tabindex="-1"></a>             <span class="at">bar =</span> <span class="cn">TRUE</span>,</span>
<span id="cb28-6"><a href="data-vis.html#cb28-6" tabindex="-1"></a>             <span class="at">hist =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                 
##  ──────────────────────────────────────────── 
##                          gender    fatigue    
##  ──────────────────────────────────────────── 
##    N                     Female         260   
##                          Male           160   
##    Missing               Female           0   
##                          Male             0   
##    Mean                  Female    47.40000   
##                          Male      48.85000   
##    Median                Female    47.00000   
##                          Male      48.00000   
##    Standard deviation    Female    3.929101   
##                          Male      4.000314   
##    Minimum               Female          41   
##                          Male            43   
##    Maximum               Female          61   
##                          Male            65   
##  ────────────────────────────────────────────</code></pre>
<p><img src="rintro_demo_files/figure-html/unnamed-chunk-14-1.png" width="672" /><img src="rintro_demo_files/figure-html/unnamed-chunk-14-2.png" width="672" /><img src="rintro_demo_files/figure-html/unnamed-chunk-14-3.png" width="672" /></p>
<p>This ability to create plots using <code>descriptives</code> is really useful, particularly when conducting exploratory data analysis. The only downside is that you do not have control about how the plots look. That’s where you will need to transition to using functions like <a href="data-vis.html#data-vis"><code>ggplot</code></a>.</p>
</div>
<div id="exercises-6" class="section level3 hasAnchor" number="8.3.3">
<h3><span class="header-section-number">8.3.3</span> Exercises<a href="data-vis.html#exercises-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><strong>Generate descriptive statistics</strong> for the <code>pain</code> and <code>fatigue</code> variables, splitting by caffeine condition. Include the mode and standard error, but not confidence intervals.</p></li>
<li><p><strong>Extend the previous exercise</strong> to also display the range and variance for each variable. What arguments do you need to change?</p></li>
<li><p><strong>Generate descriptive statistics</strong> for <code>wellb</code> and <code>age</code> variables, split by both gender and caffeine condition. Display only the mean and sample size for each variable. Your output should look like the following</p></li>
</ul>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                                
##  ─────────────────────────────────────────────────────────── 
##            gender    Condition        wellb       depr       
##  ─────────────────────────────────────────────────────────── 
##    N       Female    High Caffeine          85          85   
##                      Low Caffeine           85          85   
##                      No Caffeine            90          90   
##            Male      High Caffeine          55          55   
##                      Low Caffeine           55          55   
##                      No Caffeine            50          50   
##    Mean    Female    High Caffeine    60.42353    64.90588   
##                      Low Caffeine     56.82353    66.52941   
##                      No Caffeine      59.22222    66.01111   
##            Male      High Caffeine    58.38182    67.21818   
##                      Low Caffeine     58.23636    65.50909   
##                      No Caffeine      57.40000    67.32000   
##  ───────────────────────────────────────────────────────────</code></pre>
<ul>
<li><strong>Modify the following code</strong> to split by both gender and caffeine condition, and add density estimates (<code>dens = TRUE</code>). What changes in the plot?</li>
</ul>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="data-vis.html#cb31-1" tabindex="-1"></a><span class="fu">descriptives</span>(df_wellbeing,</span>
<span id="cb31-2"><a href="data-vis.html#cb31-2" tabindex="-1"></a>             <span class="at">vars =</span> <span class="st">&quot;age&quot;</span>,</span>
<span id="cb31-3"><a href="data-vis.html#cb31-3" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="fu">c</span>(<span class="st">&quot;gender&quot;</span>),</span>
<span id="cb31-4"><a href="data-vis.html#cb31-4" tabindex="-1"></a>             <span class="at">hist =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<ul>
<li><p><strong>Display skewness and kurtosis</strong> for the <code>wellb</code> variable, split by caffeine condition. How do these statistics help you understand the data?</p></li>
<li><p><strong>Examine the full syntax</strong> of the <code>descriptives()</code> function. What arguments could you use to check parametric assumptions for a t-test? Is anything missing?</p></li>
</ul>
<p>Okay, that’s enough for now on descriptive statistics. Let’s move on to conducting our first set of inferential statistical tests in R, the independent and paired-samples t-test.</p>
</div>
</div>
<div id="independent-samples-t-test" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Independent Samples T-Test<a href="data-vis.html#independent-samples-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s imagine we’re interested in investigating the effects of caffeine consumption on levels of fatigue. Specifically, we want to determine whether people in the <em>high caffeine</em> condition scored significantly differently from those in the <em>low caffeine</em> condition. Before we can investigate this question using t-tests, there are a couple of preliminary steps we need to take. First, since the caffeine condition currently has three levels (<code>No Caffeine</code>, <code>Low Caffeine</code>, and <code>High Caffeine</code>), we’ll need to clean our dataset by filtering out the condition we are not comparing. Second, we need to check the parametric assumptions required for an independent samples t-test.</p>
<div id="cleaning-our-data-set" class="section level3 hasAnchor" number="8.4.1">
<h3><span class="header-section-number">8.4.1</span> Cleaning our Data Set<a href="data-vis.html#cleaning-our-data-set" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Open up script <code>03-t-tests.R</code> In it, we’ll create a new data frame called <code>df_wellbeing_independent</code> by filtering out participants who were in the <code>No Caffeine</code> condition. The simplest way to do this is to tell R to exclude any rows where the <code>Condition</code> column is <code>No Caffeine</code>.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="data-vis.html#cb32-1" tabindex="-1"></a>df_wellbeing_independent <span class="ot">&lt;-</span> df_wellbeing <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="data-vis.html#cb32-2" tabindex="-1"></a>  <span class="fu">filter</span>(Condition <span class="sc">!=</span> <span class="st">&quot;No Caffeine&quot;</span>)</span></code></pre></div>
<p>Alternatively, we could also tell R to select the rows where the value for the <code>Condition</code> column is <code>Low Caffeine</code> OR (designated by <code>|</code> in R) the value for the <code>Condition</code> column is <code>High Caffeine</code>.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="data-vis.html#cb33-1" tabindex="-1"></a>df_wellbeing_independent <span class="ot">&lt;-</span> df_wellbeing <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="data-vis.html#cb33-2" tabindex="-1"></a>  <span class="fu">filter</span>(Condition <span class="sc">==</span> <span class="st">&quot;Low Caffeine&quot;</span> <span class="sc">|</span> Condition <span class="sc">==</span> <span class="st">&quot;High Caffeine&quot;</span>)</span></code></pre></div>
<p>Whichever approach you choose, it’s always a good idea to check whether your data cleaning worked as intended. We can do this using the <code>table()</code> function, which provides a frequency count of the values in the <code>Condition</code> column:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="data-vis.html#cb34-1" tabindex="-1"></a><span class="fu">table</span>(df_wellbeing_independent<span class="sc">$</span>Condition)</span></code></pre></div>
<pre><code>## 
## High Caffeine  Low Caffeine 
##           140           140</code></pre>
<p>Great! We’ve successfully removed participants from the <code>No Caffeine</code> condition.</p>
</div>
<div id="checking-our-parametric-assumptions" class="section level3 hasAnchor" number="8.4.2">
<h3><span class="header-section-number">8.4.2</span> Checking our Parametric Assumptions<a href="data-vis.html#checking-our-parametric-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are several key assumptions for conducting an independent samples t-test:</p>
<ol style="list-style-type: decimal">
<li><p>The dependent variable should be measured on a continuous scale.</p></li>
<li><p>The independent variable should consist of two categorical, independent groups.</p></li>
<li><p>The groups should be independent of each other.</p></li>
<li><p>There should be no significant outliers.</p></li>
<li><p>The dependent variable should be approximately normally distributed for each group.</p></li>
<li><p>The dependent variable should exhibit homogeneity of variance.</p></li>
</ol>
<p>We don’t need R to check the first three assumptions. A quick visual inspection of the dataset will tell us whether these are met, and in this case, they are.</p>
<div id="checking-for-outliers" class="section level4 hasAnchor" number="8.4.2.1">
<h4><span class="header-section-number">8.4.2.1</span> Checking for Outliers<a href="data-vis.html#checking-for-outliers" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Earlier, we saw that the <code>descriptives</code> function is able to product box plots. You may have noticed in the boxplot we produced earlier, it did identify several outliers. So we can use this tool again on our <code>df_wellbeing_independent</code> sample.I am setting all other default options to FALSE to reduce the amount of information printed on the screen.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="data-vis.html#cb36-1" tabindex="-1"></a><span class="fu">descriptives</span>(df_wellbeing_independent, </span>
<span id="cb36-2"><a href="data-vis.html#cb36-2" tabindex="-1"></a>             <span class="at">vars =</span> <span class="st">&quot;fatigue&quot;</span>,</span>
<span id="cb36-3"><a href="data-vis.html#cb36-3" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="st">&quot;Condition&quot;</span>,</span>
<span id="cb36-4"><a href="data-vis.html#cb36-4" tabindex="-1"></a>             <span class="at">missing =</span> <span class="cn">FALSE</span>,</span>
<span id="cb36-5"><a href="data-vis.html#cb36-5" tabindex="-1"></a>             <span class="at">n =</span> <span class="cn">FALSE</span>,</span>
<span id="cb36-6"><a href="data-vis.html#cb36-6" tabindex="-1"></a>             <span class="at">mean =</span> <span class="cn">FALSE</span>,</span>
<span id="cb36-7"><a href="data-vis.html#cb36-7" tabindex="-1"></a>             <span class="at">min =</span> <span class="cn">FALSE</span>,</span>
<span id="cb36-8"><a href="data-vis.html#cb36-8" tabindex="-1"></a>             <span class="at">median =</span> <span class="cn">FALSE</span>,</span>
<span id="cb36-9"><a href="data-vis.html#cb36-9" tabindex="-1"></a>             <span class="at">max =</span> <span class="cn">FALSE</span>,</span>
<span id="cb36-10"><a href="data-vis.html#cb36-10" tabindex="-1"></a>             <span class="at">sd =</span> <span class="cn">FALSE</span>,</span>
<span id="cb36-11"><a href="data-vis.html#cb36-11" tabindex="-1"></a>             <span class="at">box =</span> <span class="cn">TRUE</span></span>
<span id="cb36-12"><a href="data-vis.html#cb36-12" tabindex="-1"></a>             )</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES</code></pre>
<p><img src="rintro_demo_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>From the box plot, we can see that participants in rows 42, 64, 146, 200, 209, and 260 are outliers for their respective conditions. There are several ways to handle outliers, such as removing them, capping them at boundary values, or transforming them. For this example, we’ll simply remove the outliers, but I’ll also show you how to cap or transform them.</p>
<p>To remove the outliers, we can filter out any values that fall outside the interquartile range (IQR):</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="data-vis.html#cb38-1" tabindex="-1"></a>Q1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(df_wellbeing_independent<span class="sc">$</span>fatigue, <span class="fl">0.25</span>)</span>
<span id="cb38-2"><a href="data-vis.html#cb38-2" tabindex="-1"></a>Q3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(df_wellbeing_independent<span class="sc">$</span>fatigue, <span class="fl">0.75</span>)</span>
<span id="cb38-3"><a href="data-vis.html#cb38-3" tabindex="-1"></a>IQR <span class="ot">&lt;-</span> Q3 <span class="sc">-</span> Q1</span>
<span id="cb38-4"><a href="data-vis.html#cb38-4" tabindex="-1"></a></span>
<span id="cb38-5"><a href="data-vis.html#cb38-5" tabindex="-1"></a><span class="co"># Define lower and upper bounds</span></span>
<span id="cb38-6"><a href="data-vis.html#cb38-6" tabindex="-1"></a>lower_bound <span class="ot">&lt;-</span> Q1 <span class="sc">-</span> <span class="fl">1.5</span> <span class="sc">*</span> IQR</span>
<span id="cb38-7"><a href="data-vis.html#cb38-7" tabindex="-1"></a>upper_bound <span class="ot">&lt;-</span> Q3 <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> IQR</span>
<span id="cb38-8"><a href="data-vis.html#cb38-8" tabindex="-1"></a></span>
<span id="cb38-9"><a href="data-vis.html#cb38-9" tabindex="-1"></a><span class="co"># Remove outliers</span></span>
<span id="cb38-10"><a href="data-vis.html#cb38-10" tabindex="-1"></a></span>
<span id="cb38-11"><a href="data-vis.html#cb38-11" tabindex="-1"></a>df_wellbeing_independent <span class="ot">&lt;-</span> df_wellbeing_independent <span class="sc">%&gt;%</span> </span>
<span id="cb38-12"><a href="data-vis.html#cb38-12" tabindex="-1"></a>  <span class="fu">filter</span>(fatigue <span class="sc">&gt;</span> lower_bound <span class="sc">&amp;</span> fatigue <span class="sc">&lt;</span> upper_bound)</span></code></pre></div>
<p>This code calculates the interquartile range (IQR) for the fatigue variable in the df_wellbeing_independent dataset and uses it to identify and remove outliers.</p>
<p>First, it computes the first quartile (Q1) and third quartile (Q3) of fatigue using the quantile() function. The IQR is then calculated as the difference between Q3 and Q1, representing the range of the middle 50% of the data.</p>
<p>Next, the code defines the lower and upper bounds for identifying outliers. Any data points that fall more than 1.5 times the IQR below Q1 or above Q3 are considered outliers. These bounds are computed and stored in lower_bound and upper_bound.</p>
<p>Finally, the code filters the dataset to remove any rows where the fatigue values fall outside these bounds (<code>fatigue &gt; lower_bound &amp; fatigue &lt; upper_bound</code>). This step effectively removes the outliers from the df_wellbeing_independent dataset, leaving only values within the acceptable range.</p>
<p>Now let’s check to see whether we have removed these outliers by rerunning our descriptives function.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="data-vis.html#cb39-1" tabindex="-1"></a><span class="fu">descriptives</span>(df_wellbeing_independent, </span>
<span id="cb39-2"><a href="data-vis.html#cb39-2" tabindex="-1"></a>             <span class="at">vars =</span> <span class="st">&quot;fatigue&quot;</span>,</span>
<span id="cb39-3"><a href="data-vis.html#cb39-3" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="st">&quot;Condition&quot;</span>,</span>
<span id="cb39-4"><a href="data-vis.html#cb39-4" tabindex="-1"></a>             <span class="at">missing =</span> <span class="cn">FALSE</span>,</span>
<span id="cb39-5"><a href="data-vis.html#cb39-5" tabindex="-1"></a>             <span class="at">n =</span> <span class="cn">FALSE</span>,</span>
<span id="cb39-6"><a href="data-vis.html#cb39-6" tabindex="-1"></a>             <span class="at">mean =</span> <span class="cn">FALSE</span>,</span>
<span id="cb39-7"><a href="data-vis.html#cb39-7" tabindex="-1"></a>             <span class="at">min =</span> <span class="cn">FALSE</span>,</span>
<span id="cb39-8"><a href="data-vis.html#cb39-8" tabindex="-1"></a>             <span class="at">median =</span> <span class="cn">FALSE</span>,</span>
<span id="cb39-9"><a href="data-vis.html#cb39-9" tabindex="-1"></a>             <span class="at">max =</span> <span class="cn">FALSE</span>,</span>
<span id="cb39-10"><a href="data-vis.html#cb39-10" tabindex="-1"></a>             <span class="at">sd =</span> <span class="cn">FALSE</span>,</span>
<span id="cb39-11"><a href="data-vis.html#cb39-11" tabindex="-1"></a>             <span class="at">box =</span> <span class="cn">TRUE</span></span>
<span id="cb39-12"><a href="data-vis.html#cb39-12" tabindex="-1"></a>             )</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES</code></pre>
<p><img src="rintro_demo_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>Perfect! The outliers have been removed. If you’re interested in learning how to cap or transform outliers, continue reading. Otherwise, feel free to skip ahead to the next section.</p>
<p><strong><em>Capping Our Outliers</em></strong>. To cap out outliers, we can convert all outliers to a value that is considered acceptable. For example, we can set them to be the value that marks our <code>upper_bound</code> (i.e., Q3 + 1.5 * IQR) or the value that marks our <code>lower bound</code> (i.e., Q1 - 1.5 * IQR).</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="data-vis.html#cb41-1" tabindex="-1"></a>df_wellbeing_independent_capping <span class="ot">&lt;-</span> df_wellbeing_independent <span class="sc">%&gt;%</span> </span>
<span id="cb41-2"><a href="data-vis.html#cb41-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fatigue =</span> <span class="fu">case_when</span>(</span>
<span id="cb41-3"><a href="data-vis.html#cb41-3" tabindex="-1"></a>    fatigue <span class="sc">&gt;</span> upper_bound <span class="sc">~</span> upper_bound,</span>
<span id="cb41-4"><a href="data-vis.html#cb41-4" tabindex="-1"></a>    fatigue <span class="sc">&lt;</span> lower_bound <span class="sc">~</span> lower_bound,</span>
<span id="cb41-5"><a href="data-vis.html#cb41-5" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> fatigue  <span class="co"># If not an outlier, keep the original value</span></span>
<span id="cb41-6"><a href="data-vis.html#cb41-6" tabindex="-1"></a>  ))</span></code></pre></div>
<p>The code here does the following:</p>
<ul>
<li><p><code>mutate()</code> creates or modifies the <code>fatigue</code> variable in your dataset.</p></li>
<li><p><code>case_when()</code> applies different conditions to each row:</p>
<ul>
<li><p>If <code>fatigue</code> is greater than the <code>upper_bound</code>, it sets it (~) to the <code>upper_bound</code>.</p></li>
<li><p>If <code>fatigue</code> is lower than the <code>lower_bound</code>, it sets it (~) to the <code>lower_bound</code>.</p></li>
<li><p>Otherwise, it keeps the original <code>fatigue</code> value (TRUE ~ fatigue)</p></li>
</ul></li>
</ul>
<p><strong><em>Transforming Our Outliers</em></strong></p>
<p>Alternatively, we can apply a log transformation to reduce the impact of outliers. Here’s how:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="data-vis.html#cb42-1" tabindex="-1"></a>df_wellbeing_independent_log <span class="ot">&lt;-</span> df_wellbeing_independent <span class="co">#I am creating a new data frame, so we do not overwrite our other data frame with the log transformation</span></span>
<span id="cb42-2"><a href="data-vis.html#cb42-2" tabindex="-1"></a></span>
<span id="cb42-3"><a href="data-vis.html#cb42-3" tabindex="-1"></a>df_wellbeing_independent_log<span class="sc">$</span>fatigue <span class="ot">&lt;-</span> <span class="fu">log</span>(df_wellbeing_independent_log<span class="sc">$</span>fatigue) <span class="co">#this isolates the fatigue column, and then replaces it with the transformation (log) of that column. </span></span></code></pre></div>
</div>
<div id="checking-for-normality" class="section level4 hasAnchor" number="8.4.2.2">
<h4><span class="header-section-number">8.4.2.2</span> Checking for Normality<a href="data-vis.html#checking-for-normality" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>You may have spotted this in the exercises earlier, but there is a way to check for normality using the <code>descriptives</code> function. In this function, there is an argument labelled <code>sw</code> that will run a Shapiro-wilks test on the variables we select for running descriptive statistics. By default, it is set to <code>FALSE</code>, so all we need to do is set it to <code>TRUE</code>. Once again, I will turn off some of the other default options to reduce the amount of information printed, but feel free to go with the other defaults options - just make sure <code>sw</code> is set to <code>TRUE</code>.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="data-vis.html#cb43-1" tabindex="-1"></a><span class="fu">descriptives</span>(df_wellbeing_independent, </span>
<span id="cb43-2"><a href="data-vis.html#cb43-2" tabindex="-1"></a>             <span class="at">vars =</span> <span class="st">&quot;fatigue&quot;</span>,</span>
<span id="cb43-3"><a href="data-vis.html#cb43-3" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="st">&quot;Condition&quot;</span>,</span>
<span id="cb43-4"><a href="data-vis.html#cb43-4" tabindex="-1"></a>             <span class="at">median =</span> <span class="cn">FALSE</span>,</span>
<span id="cb43-5"><a href="data-vis.html#cb43-5" tabindex="-1"></a>             <span class="at">missing =</span> <span class="cn">FALSE</span>,</span>
<span id="cb43-6"><a href="data-vis.html#cb43-6" tabindex="-1"></a>             <span class="at">min =</span> <span class="cn">FALSE</span>,</span>
<span id="cb43-7"><a href="data-vis.html#cb43-7" tabindex="-1"></a>             <span class="at">max =</span> <span class="cn">FALSE</span>,</span>
<span id="cb43-8"><a href="data-vis.html#cb43-8" tabindex="-1"></a>             <span class="at">sw =</span> <span class="cn">TRUE</span></span>
<span id="cb43-9"><a href="data-vis.html#cb43-9" tabindex="-1"></a>             )</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                         
##  ──────────────────────────────────────────────────── 
##                          Condition        fatigue     
##  ──────────────────────────────────────────────────── 
##    N                     High Caffeine          136   
##                          Low Caffeine           138   
##    Mean                  High Caffeine     47.38971   
##                          Low Caffeine      47.72464   
##    Standard deviation    High Caffeine     3.338158   
##                          Low Caffeine      3.854598   
##    Shapiro-Wilk W        High Caffeine    0.9577953   
##                          Low Caffeine     0.9429279   
##    Shapiro-Wilk p        High Caffeine    0.0003363   
##                          Low Caffeine     0.0000196   
##  ────────────────────────────────────────────────────</code></pre>
<p>We can see two new values in our descriptive table, the test statistic <code>Shapiro-Wilk W</code> and its corresponding p-value <code>Shapiro-Wilk p</code>. We can see that for both the High Caffeine and Low Caffeine condition, we have not met this assumption. In real life, we should do something about this, or at least run a non-parametric test. But I am going to pretend it’s not a big deal for the time being.</p>
</div>
</div>
<div id="checking-for-homogeneity-of-variance" class="section level3 hasAnchor" number="8.4.3">
<h3><span class="header-section-number">8.4.3</span> Checking for Homogeneity of Variance<a href="data-vis.html#checking-for-homogeneity-of-variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Hopefully, you will also have spotted in the exercises earlier that <code>descriptives</code> does not compute a Levene’s Test for measuring Homogeneity of Variance. To do that, we need to a function in the <code>car</code> package that is called <code>leveneTest</code>. The syntax for this function is as follows: ``</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="data-vis.html#cb45-1" tabindex="-1"></a><span class="fu">leveneTest</span>(DependentVariable <span class="sc">~</span> IndependentVariable, <span class="at">data =</span> ourdataset)</span></code></pre></div>
<p>Let’s use this to assess whether <code>fatigue</code> exhibits homogeneity of variance across the two caffeine conditions.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="data-vis.html#cb46-1" tabindex="-1"></a><span class="fu">leveneTest</span>(fatigue <span class="sc">~</span> Condition, <span class="at">data =</span> df_wellbeing_independent)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   1  1.7003 0.1934
##       272</code></pre>
<p>Luckily, we can see that our data has met this parametric assumption. So let’s proceed on and run our t-test.</p>
</div>
<div id="running-an-independent-sample-t-test" class="section level3 hasAnchor" number="8.4.4">
<h3><span class="header-section-number">8.4.4</span> Running an Independent Sample T-Test<a href="data-vis.html#running-an-independent-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use the <code>t.test</code> function to perform the t-test. The syntax is:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="data-vis.html#cb48-1" tabindex="-1"></a><span class="fu">t.test</span>(DV <span class="sc">~</span> IV, </span>
<span id="cb48-2"><a href="data-vis.html#cb48-2" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb48-3"><a href="data-vis.html#cb48-3" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">&quot;two.sided&quot;</span>, <span class="st">&quot;less&quot;</span>, <span class="st">&quot;greater&quot;</span>),</span>
<span id="cb48-4"><a href="data-vis.html#cb48-4" tabindex="-1"></a>       <span class="at">data =</span> ourdataset)</span></code></pre></div>
<p>In this function:</p>
<ul>
<li><p><code>DV ~ IV</code> specifies the dependent variable (DV) and independent variable (IV).</p></li>
<li><p><code>paired = FALSE</code> indicates that we are conducting an independent samples t-test. If we were comparing related groups (e.g., pre-test vs. post-test), we would set <code>paired = TRUE</code>.</p></li>
<li><p>The <code>alternative</code> argument specifies the hypothesis test type:</p>
<ul>
<li><p><code>"two.sided"</code> tests for any difference between groups.</p></li>
<li><p><code>"less"</code> tests whether the first group has a lower mean than the second.</p></li>
<li><p><code>"greater"</code> tests whether the first group has a higher mean than the second.</p></li>
</ul></li>
</ul>
<p>Let’s run the two-sided test on our <code>df_wellbeing_independent</code> dataset:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="data-vis.html#cb49-1" tabindex="-1"></a><span class="fu">t.test</span>(fatigue <span class="sc">~</span> Condition, </span>
<span id="cb49-2"><a href="data-vis.html#cb49-2" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,</span>
<span id="cb49-3"><a href="data-vis.html#cb49-3" tabindex="-1"></a>       <span class="at">data =</span> df_wellbeing_independent)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  fatigue by Condition
## t = -0.76919, df = 267.59, p-value = 0.4425
## alternative hypothesis: true difference in means between group High Caffeine and group Low Caffeine is not equal to 0
## 95 percent confidence interval:
##  -1.1922429  0.5223793
## sample estimates:
## mean in group High Caffeine  mean in group Low Caffeine 
##                    47.38971                    47.72464</code></pre>
<p>The t-test results show no significant difference in fatigue levels between the High Caffeine and Low Caffeine groups.</p>
<p>Here’s how we might write up the results in APA style:</p>
<p><code>A Welch two-sample t-test was conducted to compare fatigue levels between participants in the High Caffeine and Low Caffeine conditions. The test showed that there was no significant difference in the means of fatigue between the two groups, t(267.59) = -0.77, p = 0.44. One fails to reject the null hypothesis.</code></p>
<ol style="list-style-type: decimal">
<li><p>Run an independent samples t-test investigating whether there is an effect of <code>No Caffeine</code> versus <code>High Caffeine</code> on <code>fatigue</code>. Remember to use the <code>filter</code> function and check parametric assumptions.</p></li>
<li><p>Run an independent samples t-test investigating whether there is an effect of <code>gender</code> on wellbeing (<code>wellb</code>). Remember to check parametric assumptions.</p></li>
</ol>
</div>
</div>
<div id="paired-samples-t-test" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Paired-Samples T-Test<a href="data-vis.html#paired-samples-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The process for running a paired-samples t-test is very similar to an independent t-test, so this section will be relatively brief. We will use the <code>df_psycho</code> dataset, which was imported earlier in the set-up section.</p>
<p>Let’s start by examining the dataset using the <code>head()</code> function.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="data-vis.html#cb51-1" tabindex="-1"></a><span class="fu">head</span>(df_psycho)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   Participant_ID Treatment Neuroticism
##            &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt;
## 1              1 Placebo          39.4
## 2              2 Placebo          42.7
## 3              3 Placebo          60.6
## 4              4 Placebo          45.7
## 5              5 Placebo          46.3
## 6              6 Placebo          62.2</code></pre>
<p>This dataset comes from a study that evaluated the effect of psychoactive drugs (Treatment with three levels: DMT, Psilocybin, and Placebo) on total Neuroticism scores. The study used a within-subjects design, meaning that each participant took all three treatments (DMT, Psilocybin, and Placebo), and their Neuroticism score was measured the day after each treatment.</p>
<p>In this section, we will investigate whether there is a significant difference in Neuroticism scores between the Psilocybin and DMT conditions.</p>
<div id="cleaning-our-data-set-1" class="section level3 hasAnchor" number="8.5.1">
<h3><span class="header-section-number">8.5.1</span> Cleaning our Data Set<a href="data-vis.html#cleaning-our-data-set-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ll create a data frame called <code>df_psycho_paired</code> by filtering out all observations from the Placebo condition. The easiest way to do this is by excluding rows where the value in the <code>Treatment</code> column is “Placebo”.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="data-vis.html#cb53-1" tabindex="-1"></a>df_psycho_paired <span class="ot">&lt;-</span> df_psycho <span class="sc">%&gt;%</span> </span>
<span id="cb53-2"><a href="data-vis.html#cb53-2" tabindex="-1"></a>  <span class="fu">filter</span>(Treatment <span class="sc">!=</span> <span class="st">&quot;Placebo&quot;</span>)</span></code></pre></div>
<p>Alternatively, we could also tell R to select the rows where the value for the <code>Treatment</code> column is <code>Psilocybin</code> OR (designated by <code>|</code> in R) the value for the <code>Treatment</code> column is <code>DMT</code>.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="data-vis.html#cb54-1" tabindex="-1"></a>df_psycho_paired <span class="ot">&lt;-</span> df_psycho <span class="sc">%&gt;%</span> </span>
<span id="cb54-2"><a href="data-vis.html#cb54-2" tabindex="-1"></a>  <span class="fu">filter</span>(Treatment <span class="sc">==</span> <span class="st">&quot;Psilocybin&quot;</span> <span class="sc">|</span> Treatment <span class="sc">==</span> <span class="st">&quot;DMT&quot;</span>)</span></code></pre></div>
<p>Whichever approach you use, it’s important to check if your data cleaning worked as intended. We can do this with the <code>table()</code> function:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="data-vis.html#cb55-1" tabindex="-1"></a><span class="fu">table</span>(df_psycho_paired<span class="sc">$</span>Treatment)</span></code></pre></div>
<pre><code>## 
##        DMT Psilocybin 
##         20         20</code></pre>
<p>Great! We’ve successfully removed observations from the Placebo condition.</p>
</div>
<div id="checking-our-parametric-assumptions-1" class="section level3 hasAnchor" number="8.5.2">
<h3><span class="header-section-number">8.5.2</span> Checking our Parametric Assumptions<a href="data-vis.html#checking-our-parametric-assumptions-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are several assumptions to the Paired Sample T-Test</p>
<ul>
<li>Our dependent variable should be measured on a continuous scale</li>
<li>Our independent variable should consist of two categorical group that are related or have matched pairs.</li>
<li>The groups should be independent from each</li>
<li>There should be no significant outliers</li>
<li>Our dependent variable should be normally distributed</li>
</ul>
<p>Again, it’s only really the outliers and the normal distribution that needs to be evaluated using functions in R.</p>
<div id="checking-for-outliers-and-normality." class="section level4 hasAnchor" number="8.5.2.1">
<h4><span class="header-section-number">8.5.2.1</span> Checking for Outliers and Normality.<a href="data-vis.html#checking-for-outliers-and-normality." class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can use the <code>descriptives</code> function to calculate descriptive statistics for the Neuroticism scores, check for outliers with a box plot, and assess normality using the Shapiro-Wilk test (<code>sw = TRUE</code>). To get a fuller picture, we’ll also produce a density (<code>dens = TRUE</code>) histogram (<code>hist = TRUE</code>) and a Q-Q plot (<code>qq = TRUE</code>).</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="data-vis.html#cb57-1" tabindex="-1"></a><span class="fu">descriptives</span>(df_psycho_paired, </span>
<span id="cb57-2"><a href="data-vis.html#cb57-2" tabindex="-1"></a>             <span class="at">vars =</span> <span class="st">&quot;Neuroticism&quot;</span>,</span>
<span id="cb57-3"><a href="data-vis.html#cb57-3" tabindex="-1"></a>             <span class="at">splitBy =</span> <span class="st">&quot;Treatment&quot;</span>,</span>
<span id="cb57-4"><a href="data-vis.html#cb57-4" tabindex="-1"></a>             <span class="at">box =</span> <span class="cn">TRUE</span>,</span>
<span id="cb57-5"><a href="data-vis.html#cb57-5" tabindex="-1"></a>             <span class="at">sw =</span> <span class="cn">TRUE</span>,</span>
<span id="cb57-6"><a href="data-vis.html#cb57-6" tabindex="-1"></a>             <span class="at">hist =</span> <span class="cn">TRUE</span>,</span>
<span id="cb57-7"><a href="data-vis.html#cb57-7" tabindex="-1"></a>             <span class="at">dens =</span> <span class="cn">TRUE</span>,</span>
<span id="cb57-8"><a href="data-vis.html#cb57-8" tabindex="-1"></a>             <span class="at">qq =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                                        
##  ─────────────────────────────────────────────────── 
##                          Treatment     Neuroticism   
##  ─────────────────────────────────────────────────── 
##    N                     DMT                    20   
##                          Psilocybin             20   
##    Missing               DMT                     0   
##                          Psilocybin              0   
##    Mean                  DMT              44.48743   
##                          Psilocybin       56.06485   
##    Median                DMT              43.60057   
##                          Psilocybin       54.64291   
##    Standard deviation    DMT              8.299387   
##                          Psilocybin       9.573406   
##    Minimum               DMT              28.13307   
##                          Psilocybin       39.51247   
##    Maximum               DMT              57.53815   
##                          Psilocybin       76.68956   
##    Shapiro-Wilk W        DMT             0.9559402   
##                          Psilocybin      0.9739320   
##    Shapiro-Wilk p        DMT             0.4662564   
##                          Psilocybin      0.8347337   
##  ───────────────────────────────────────────────────</code></pre>
<p><img src="rintro_demo_files/figure-html/unnamed-chunk-34-1.png" width="672" /><img src="rintro_demo_files/figure-html/unnamed-chunk-34-2.png" width="672" /><img src="rintro_demo_files/figure-html/unnamed-chunk-34-3.png" width="672" /></p>
<p>The dataset does not violate either assumption. Let’s go ahead and run our paired-samples t-test.</p>
</div>
</div>
<div id="running-the-test" class="section level3 hasAnchor" number="8.5.3">
<h3><span class="header-section-number">8.5.3</span> Running the Test<a href="data-vis.html#running-the-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To run the paired-samples t-test, we use the <code>t.test</code> function, but this time we set the <code>paired</code> argument to <code>TRUE</code> to indicate that the two groups are related.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="data-vis.html#cb59-1" tabindex="-1"></a><span class="fu">t.test</span>(Neuroticism <span class="sc">~</span> Treatment,</span>
<span id="cb59-2"><a href="data-vis.html#cb59-2" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb59-3"><a href="data-vis.html#cb59-3" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,</span>
<span id="cb59-4"><a href="data-vis.html#cb59-4" tabindex="-1"></a>       <span class="at">data =</span> df_psycho_paired)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  Neuroticism by Treatment
## t = -4.2999, df = 19, p-value = 0.0003865
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -17.212882  -5.941966
## sample estimates:
## mean difference 
##       -11.57742</code></pre>
<p>That’s it! We have successfully conducted a paired-samples t-test. Here’s how we would write up the results in APA style:</p>
<p>A paired samples t-test was conducted to examine whether there was a significant difference in Neuroticism scores after participants took the psychoactive drugs Psilocybin and DMT. The test revealed a statistically significant reduction in Neuroticism after the DMT treatment compared to the Psilocybin treatment, t(19) = -4.30, p ≤ .001. This suggests that the treatment had a significant effect on neuroticism scores.</p>
</div>
<div id="exercises-7" class="section level3 hasAnchor" number="8.5.4">
<h3><span class="header-section-number">8.5.4</span> Exercises<a href="data-vis.html#exercises-7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>Run a paired-samples t-test to investigate the effects of Psilocybin on Neuroticism compared to the Placebo. Ensure that you check your parametric assumptions.</p></li>
<li><p>Run a paired-samples t-test to investigate the effects of DMT on Neuroticism compared to the Placebo. Again, make sure to check the parametric assumptions.</p></li>
</ol>
</div>
</div>
<div id="power-analysis" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> Power Analysis<a href="data-vis.html#power-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can also conduct power analysis in R when running t-tests via the <code>pwr</code> package we loaded in earlier.</p>
<div id="independent-samples-apriori" class="section level3 hasAnchor" number="8.6.1">
<h3><span class="header-section-number">8.6.1</span> Independent Samples (Apriori)<a href="data-vis.html#independent-samples-apriori" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The syntax for conducting an apriori statistical power analysis for an independent samples t-test is the following</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="data-vis.html#cb61-1" tabindex="-1"></a><span class="co"># Load the pwr package</span></span>
<span id="cb61-2"><a href="data-vis.html#cb61-2" tabindex="-1"></a><span class="fu">library</span>(pwr)</span>
<span id="cb61-3"><a href="data-vis.html#cb61-3" tabindex="-1"></a></span>
<span id="cb61-4"><a href="data-vis.html#cb61-4" tabindex="-1"></a><span class="co"># Conduct power analysis for an independent samples t-test</span></span>
<span id="cb61-5"><a href="data-vis.html#cb61-5" tabindex="-1"></a><span class="fu">pwr.t.test</span>(<span class="at">d =</span> <span class="fl">0.5</span>,         <span class="co"># Your Expected effect size</span></span>
<span id="cb61-6"><a href="data-vis.html#cb61-6" tabindex="-1"></a>           <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="co"># Significance level</span></span>
<span id="cb61-7"><a href="data-vis.html#cb61-7" tabindex="-1"></a>           <span class="at">power =</span> <span class="fl">0.80</span>,     <span class="co"># Desired power level</span></span>
<span id="cb61-8"><a href="data-vis.html#cb61-8" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">&quot;two.sample&quot;</span>,  <span class="co"># Indicates an independent t-test</span></span>
<span id="cb61-9"><a href="data-vis.html#cb61-9" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)  <span class="co"># Indicates a two-tailed test, #can be changed to &quot;one.sided&quot;</span></span></code></pre></div>
<p>We can apply this syntax to <code>df_wellbeing_independent</code> data set. I am going to assume a large effect size (d = .70)</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="data-vis.html#cb62-1" tabindex="-1"></a><span class="co"># Conduct power analysis for an independent samples t-test</span></span>
<span id="cb62-2"><a href="data-vis.html#cb62-2" tabindex="-1"></a><span class="fu">pwr.t.test</span>(<span class="at">d =</span> <span class="fl">0.7</span>,         </span>
<span id="cb62-3"><a href="data-vis.html#cb62-3" tabindex="-1"></a>           <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="co"># Significance level</span></span>
<span id="cb62-4"><a href="data-vis.html#cb62-4" tabindex="-1"></a>           <span class="at">power =</span> <span class="fl">0.80</span>,     <span class="co"># Desired power level</span></span>
<span id="cb62-5"><a href="data-vis.html#cb62-5" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">&quot;two.sample&quot;</span>,  </span>
<span id="cb62-6"><a href="data-vis.html#cb62-6" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)  </span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 33.02457
##               d = 0.7
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
</div>
<div id="paired-samples-apriorio" class="section level3 hasAnchor" number="8.6.2">
<h3><span class="header-section-number">8.6.2</span> Paired Samples (Apriorio)<a href="data-vis.html#paired-samples-apriorio" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If we want to run a paired samples-test, then we can change the type from “two.sample” to “one.sample”.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="data-vis.html#cb64-1" tabindex="-1"></a><span class="co"># Load the pwr package</span></span>
<span id="cb64-2"><a href="data-vis.html#cb64-2" tabindex="-1"></a><span class="fu">library</span>(pwr)</span>
<span id="cb64-3"><a href="data-vis.html#cb64-3" tabindex="-1"></a></span>
<span id="cb64-4"><a href="data-vis.html#cb64-4" tabindex="-1"></a><span class="co"># Conduct power analysis for an independent samples t-test</span></span>
<span id="cb64-5"><a href="data-vis.html#cb64-5" tabindex="-1"></a><span class="fu">pwr.t.test</span>(<span class="at">d =</span> <span class="fl">0.5</span>,         <span class="co"># Your Expected effect size</span></span>
<span id="cb64-6"><a href="data-vis.html#cb64-6" tabindex="-1"></a>           <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="co"># Significance level</span></span>
<span id="cb64-7"><a href="data-vis.html#cb64-7" tabindex="-1"></a>           <span class="at">power =</span> <span class="fl">0.80</span>,     <span class="co"># Desired power level</span></span>
<span id="cb64-8"><a href="data-vis.html#cb64-8" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">&quot;paired&quot;</span>,  <span class="co"># Indicates an independent t-test</span></span>
<span id="cb64-9"><a href="data-vis.html#cb64-9" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)  <span class="co"># Indicates a two-tailed test, #can be changed to &quot;one.sided&quot;</span></span></code></pre></div>
<p>We can apply this syntax to <code>df_psycho_paired</code> data set. I am going to assume a small effect size (d = .20)</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="data-vis.html#cb65-1" tabindex="-1"></a><span class="co"># Conduct power analysis for an independent samples t-test</span></span>
<span id="cb65-2"><a href="data-vis.html#cb65-2" tabindex="-1"></a><span class="fu">pwr.t.test</span>(<span class="at">d =</span> <span class="fl">0.2</span>,         </span>
<span id="cb65-3"><a href="data-vis.html#cb65-3" tabindex="-1"></a>           <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="co"># Significance level</span></span>
<span id="cb65-4"><a href="data-vis.html#cb65-4" tabindex="-1"></a>           <span class="at">power =</span> <span class="fl">0.80</span>,     <span class="co"># Desired power level</span></span>
<span id="cb65-5"><a href="data-vis.html#cb65-5" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">&quot;paired&quot;</span>,  </span>
<span id="cb65-6"><a href="data-vis.html#cb65-6" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)  </span></code></pre></div>
<pre><code>## 
##      Paired t test power calculation 
## 
##               n = 198.1508
##               d = 0.2
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number of *pairs*</code></pre>
</div>
<div id="post-hoc-tests" class="section level3 hasAnchor" number="8.6.3">
<h3><span class="header-section-number">8.6.3</span> Post-Hoc Tests<a href="data-vis.html#post-hoc-tests" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To run a post-hoc power analysis, we need to set the <code>n</code> (sample size) instead of the <code>power</code> argument, and leave <code>power = NULL</code>. Here is how we can do that for an independent-samples t-test</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="data-vis.html#cb67-1" tabindex="-1"></a><span class="fu">pwr.t.test</span>(<span class="at">d =</span> <span class="fl">0.7</span>,         </span>
<span id="cb67-2"><a href="data-vis.html#cb67-2" tabindex="-1"></a>           <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="co"># Significance level</span></span>
<span id="cb67-3"><a href="data-vis.html#cb67-3" tabindex="-1"></a>           <span class="at">n =</span> <span class="dv">420</span>,</span>
<span id="cb67-4"><a href="data-vis.html#cb67-4" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">&quot;two.sample&quot;</span>,  </span>
<span id="cb67-5"><a href="data-vis.html#cb67-5" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)  </span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 420
##               d = 0.7
##       sig.level = 0.05
##           power = 1
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>And for a paired-samples t-test</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="data-vis.html#cb69-1" tabindex="-1"></a><span class="fu">pwr.t.test</span>(<span class="at">d =</span> <span class="fl">0.2</span>,         </span>
<span id="cb69-2"><a href="data-vis.html#cb69-2" tabindex="-1"></a>           <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="co"># Significance level</span></span>
<span id="cb69-3"><a href="data-vis.html#cb69-3" tabindex="-1"></a>           <span class="at">n =</span> <span class="dv">20</span>,</span>
<span id="cb69-4"><a href="data-vis.html#cb69-4" tabindex="-1"></a>           <span class="at">type =</span> <span class="st">&quot;paired&quot;</span>,  </span>
<span id="cb69-5"><a href="data-vis.html#cb69-5" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)  </span></code></pre></div>
<pre><code>## 
##      Paired t test power calculation 
## 
##               n = 20
##               d = 0.2
##       sig.level = 0.05
##           power = 0.1359563
##     alternative = two.sided
## 
## NOTE: n is number of *pairs*</code></pre>
</div>
<div id="exercises-8" class="section level3 hasAnchor" number="8.6.4">
<h3><span class="header-section-number">8.6.4</span> Exercises<a href="data-vis.html#exercises-8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Run an <em>a priori</em> power analysis for the independent samples t-test you ran in the exercises. Set the expected effect size to <em>d</em> = 0.40.</li>
</ul>
<!-- -->
<ul>
<li>Run a <em>post-hoc</em> power analysis for the paired samples t-test you ran in the exercises. Use the observed effect size from your results and sample size to calculate the power of your study.</li>
</ul>
</div>
</div>
<div id="summary-10" class="section level2 hasAnchor" number="8.7">
<h2><span class="header-section-number">8.7</span> Summary<a href="data-vis.html#summary-10" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Well done. We’ve learnt how to run descriptive statistics, paired-samples, and independent samples t-tests in R. You might have noticed how straightforward it is to actually run the tests themselves - it just took a couple of lines of code. This is nearly always the case when running inferential statistics in R. The hard part is cleaning and visualising the data, the tests themselves are quick and easy. In the next session, we’ll learn how to run ANOVAs, before moving on to our final topics, correlation and regression.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>In fairness, there are elegant ways around this using base R that are nice. But I am still using the `descriptives` function because it enables us to do other cool things, like create graphs.<a href="data-vis.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-vis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix---understanding-boolean-operators-in-the-context-of-filter.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/cjvanlissa/gitbook-demo/edit/master/08-descriptives-t-tests.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["rintro_demo.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
